export interface Article {
  slug: string;
  title: string;
  summary: string;
  category: string;
  date: string;
  author: string;
  image: string;
  readTime: string;
  keywords: string[];
  content: string[];
}

export const articlesData: Article[] = [
  {
    slug: "cam-nang-chon-mua-bo-do-tho-bang-dong-y-yen-nam-dinh",
    title: "Cẩm Nang Chọn Mua Bộ Đồ Thờ Bằng Đồng Ý Yên Nam Định: Phân Biệt Chất Liệu, Thước Lỗ Ban & Bảng Giá Xưởng 2026",
    summary: "Hướng dẫn toàn diện từ nghệ nhân xưởng đúc Lộc Nam: Cấu tạo bộ tam sự ngũ sự, phân biệt 4 loại đồng (đồng đỏ, đồng vàng, cát tút, mạ vàng 24k), bảng tra thước Lỗ Ban 38.8cm và báo giá tận xưởng không qua trung gian.",
    category: "CẨM NANG PHONG THỦY",
    date: "12/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/locnam_bo_do_tho.jpg",
    readTime: "12 phút đọc",
    keywords: [
      "bộ đồ thờ bằng đồng",
      "đồ thờ cúng nam định",
      "đồ đồng lộc nam",
      "đỉnh đồng ý yên",
      "bộ ngũ sự bằng đồng",
      "báo giá đồ thờ bằng đồng",
      "thước lỗ ban bàn thờ",
      "đồ đồng đẹp nam định",
      "phân biệt đồng đỏ đồng thau",
      "cách bày bàn thờ gia tiên"
    ],
    content: [
      "Trong văn hóa tâm linh của người Việt, không gian thờ cúng gia tiên là nơi tôn nghiêm nhất trong mỗi gia đình, thể hiện lòng hiếu kính 'Uống nước nhớ nguồn' đối với tổ tiên, cội nguồn. Trong đó, bộ đồ thờ bằng đồng luôn là lựa chọn hàng đầu của các gia đình danh gia, quyền quý bởi vẻ đẹp uy nghiêm, độ bền trường tồn hàng trăm năm và ý nghĩa phong thủy hội tụ linh khí ngũ hành.",
      "Tuy nhiên, trước sự xuất hiện tràn lan của các dòng đồng pha chì, đồng Đài Loan dập máy mạ xi mỏng chỉ sau vài năm là xỉn ố, việc tìm mua được một bộ đồ thờ bằng đồng chuẩn làng nghề Ý Yên Nam Định nguyên chất, đúc thủ công tinh xảo là nỗi băn khoăn của rất nhiều gia chủ.",
      "Bài viết cẩm nang dưới đây của Xưởng Đúc Đồng Lộc Nam sẽ cung cấp cho bạn cái nhìn toàn diện từ cấu tạo bộ tam sự - ngũ sự, cách phân biệt các loại đồng, bảng tra kích thước theo thước Lỗ Ban và bảng báo giá chi tiết tận xưởng năm 2026.",
      "## PHẦN 1: CẤU TẠO BỘ ĐỒ THỜ BẰNG ĐỒNG GỒM NHỮNG GÌ? PHÂN BIỆT BỘ TAM SỰ VÀ BỘ NGŨ SỰ",
      "Tùy thuộc vào diện tích bàn thờ gia tiên và điều kiện của từng gia đình, bộ đồ thờ bằng đồng thường được chia làm 2 quy cách chính: Bộ Tam Sự (3 món) và Bộ Ngũ Sự (5 món).",
      "### 1. Đỉnh Đồng (Lư Hương) – Trái Tim Của Bàn Thờ Gia Tiên",
      "Đỉnh đồng là pháp bảo ngự tại vị trí chính giữa bàn thờ, dùng để đốt trầm hương trong các ngày mùng Một, ngày Rằm và lễ Tết.",
      "- Ý nghĩa tâm linh: Khói trầm thơm thanh khiết tỏa ra từ miệng nghê trên nắp đỉnh có tác dụng thanh tẩy tà khí, hóa giải hung khí, kích hoạt vượng khí và kết nối lòng thành của con cháu với tổ tiên nơi cõi thiêng.",
      "- Nắp đỉnh: Đúc nổi hình tượng Con Nghê vờn cầu – linh vật thuần Việt có linh lực trấn trạch, xua đuổi tà ma và bảo hộ gia trạch bình an.",
      "- Thân đỉnh: Bầu tròn hoặc vuông quả bóng, chạm khắc nổi bộ chữ Hán - Nôm mạ vàng 'Phúc - Lộc - Thọ - Khang - Ninh' kết hợp họa tiết Song Long Chầu Nguyệt tinh xảo.",
      "- Tai mây (Quai đỉnh): Đúc liền khối với thân đỉnh, uốn lượn hình mây cách điệu vững chãi.",
      "- Chân đỉnh: 3 chân đúc liền thân theo thế 'kiềng ba chân', chạm khắc đầu hổ phù uy nghiêm chống đỡ bầu đỉnh.",
      "- Đế đỉnh: Dáng tròn hoặc bát giác, vừa khít với 3 chân đỉnh, mặt trên chạm hoa văn rồng cuộn hoặc hoa sen thanh tịnh.",
      "### 2. Đôi Hạc Đồng Cưỡi Kim Quy – Biểu Tượng Trường Thọ & Tương Trợ Âm Dương",
      "Đặt đối xứng hai bên đỉnh đồng là đôi hạc đứng trên lưng rùa, đầu ngẩng cao, miệng ngậm cành hoa sen.",
      "- Hạc: Loài chim tiên cao quý, đại diện cho phẩm hạnh thanh cao, sự thuần khiết và khí tiết của người quân tử.",
      "- Rùa (Kim Quy): Loài bò sát trường thọ, đại diện cho đất mẹ vững chãi và sự bền bỉ chở che.",
      "- Triết lý nhân sinh: Hạc đứng trên lưng rùa tượng trưng cho tình nghĩa tương trợ keo sơn giữa trời và đất, âm và dương, nhắc nhở con cháu luôn sống hòa thuận, hiếu thảo và kiên định trước sóng gió cuộc đời.",
      "### 3. Đôi Chân Nến (Đèn Thờ) – Ánh Sáng Trí Tuệ & Nhật Nguyệt Giao Hòa",
      "Được đặt ở phía ngoài cùng hai bên bàn thờ, phía trước hoặc ngang hàng với đôi hạc:",
      "- Chân nến bên trái tượng trưng cho Mặt Trời (Dương khí).",
      "- Chân nến bên phải tượng trưng cho Mặt Trăng (Âm khí).",
      "- Sự hiện diện của đôi chân nến mang ý nghĩa nhật nguyệt giao hòa, sinh sôi nảy nở, soi đường chỉ lối cho con cháu hướng về đạo đức, công danh và sự nghiệp hanh thông.",
      "## PHẦN 2: KHOA HỌC LUYỆN KIM – CÁCH PHÂN BIỆT 4 CHẤT LIỆU ĐỒNG PHỔ BIẾN TRÊN THỊ TRƯỜNG",
      "Chất liệu đúc quyết định tới 80% giá trị và tuổi thọ của một bộ đồ thờ. Dưới đây là đặc tính 4 dòng đồng đang có trên thị trường hiện nay:",
      "### 1. Đồng Vàng Thau (Đồng Thau)",
      "- Thành phần: Đồng thanh khiết 65% - 70% kết hợp hợp kim kẽm để tăng độ chảy lỏng.",
      "- Màu sắc: Màu vàng sáng bóng tự nhiên hoặc hun rêu cổ trang nghiêm.",
      "- Trọng lượng: Bộ 60cm nặng khoảng 22kg - 25kg.",
      "- Độ bền: 20 - 30 năm, thích hợp cho phân khúc gia đình cần sự trang trọng với chi phí hợp lý.",
      "### 2. Đồng Đỏ Nguyên Chất (Đồng Mắt Cua)",
      "- Thành phần: Đồng đỏ thanh khiết 90% - 95% (sử dụng dây cáp điện đỏ tuyển chọn loại 1).",
      "- Màu sắc: Màu đỏ mắt cua trầm ấm, bóng mịn, càng dùng theo năm tháng càng lên nước cổ kính.",
      "- Trọng lượng: Bộ 60cm nặng từ 28kg - 32kg, cầm rất đầm tay và chắc chắn.",
      "- Độ bền: Trường tồn trên 70 năm, không lo nứt vỡ hay bay màu.",
      "### 3. Đồng Cát-Tút (Vỏ Đạn Pháo Quân Sự)",
      "- Thành phần: Đúc từ vỏ đạn pháo quân sự nguyên chất, tính dẻo và độ đanh cơ học cực cao.",
      "- Màu sắc: Ánh vàng xanh quân sự đặc trưng, âm thanh gõ vang ngân như tiếng chuông khánh.",
      "- Độ bền: Vĩnh cửu trên 80 năm, thuộc phân khúc thượng lưu.",
      "### 4. Đồng Khảm Tam Khí / Ngũ Sắc & Mạ Vàng 24K",
      "- Cốt đồng đỏ thanh khiết chạm khắc âm bản, sau đó nghệ nhân dùng búa gõ nạm từng lá Bạc 9999 và Vàng 24k nguyên chất vào từng đường hoa văn.",
      "- Đỉnh cao mỹ nghệ truyền thống, độ tinh xảo bậc nhất, giá trị truyền đời hàng trăm năm cho con cháu.",
      "> Lời khuyên của nghệ nhân Lộc Nam: Đối với bàn thờ gia tiên lâu dài, gia chủ nên ưu tiên lựa chọn chất liệu từ Đồng Đỏ nguyên khối hoặc Đồng Cát-Tút trở lên. Đồng đỏ có tính hàn, trầm mặc, rất hợp với chốn thờ tự linh thiêng.",
      "## PHẦN 3: BẢNG TRA KÍCH THƯỚC BỘ ĐỒ THỜ THEO THƯỚC LỖ BAN CHUẨN KÍCH THƯỚC BÀN THỜ",
      "Một sai lầm rất phổ biến là gia chủ chọn bộ đỉnh quá to khiến bàn thờ chật chội, hoặc chọn bộ đỉnh quá nhỏ khiến không gian thờ bị lọt thỏm. Dưới đây là bảng quy chuẩn vàng từ xưởng Lộc Nam:",
      "- Bàn thờ dài 1m27 đến 1m55 (Sâu 61cm - 69cm): Phù hợp với bộ đỉnh đồng cao 45cm (Cung Tiến Bảo, Thêm Đinh). Khuyên dùng bộ Tam sự 45cm.",
      "- Bàn thờ dài 1m75 đến 1m97 (Sâu 81cm - 97cm): Phù hợp với bộ đỉnh đồng cao 50cm hoặc 60cm (Cung Đăng Khoa, Tài Lộc). Đây là kích thước chuẩn mực phổ biến nhất cho gia đình Việt.",
      "- Bàn thờ dài 1m97 đến 2m17 (Sâu 97cm - 107cm): Phù hợp với bộ đỉnh đồng cao 65cm hoặc 70cm (Cung Đại Cát, Quý Tử).",
      "- Bàn thờ Tổ, Từ đường, Nhà thờ họ (Dài trên 2m17): Phù hợp với bộ đỉnh đồng cao 70cm trở lên kết hợp đôi hạc đứng sàn 1m60 hoặc 1m80 uy nghi.",
      "## PHẦN 4: HƯỚNG DẪN BÀY TRÍ BÀN THỜ GIA TIÊN ĐÚNG NGUYÊN TẮC 'ĐÔNG BÌNH TÂY QUẢ'",
      "Việc sắp đặt bộ đồ thờ đúng phương vị phong thủy giúp tụ khí sinh tài, con cháu trong nhà thuận hòa, học hành đỗ đạt:",
      "- 1. Đỉnh đồng: Đặt ở vị trí chính giữa bàn thờ, lùi về phía sau cùng (sát vách tường hoặc khám thờ). Nắp nghê quay mặt nhìn thẳng ra phía trước cửa phòng thờ.",
      "- 2. Đôi Hạc: Đặt chầu hai bên đỉnh đồng, mỏ hạc hướng vào thân đỉnh. Khoảng cách từ thân đỉnh tới chân hạc từ 5cm - 10cm.",
      "- 3. Đôi Chân nến: Đặt đối xứng hai bên ngoài đôi hạc, hơi chếch về phía trước của bàn thờ để thuận tiện thắp nến ngày rằm và tạo ánh sáng ấm áp.",
      "- 4. Bát hương: Ngự tại chính diện phía trước Đỉnh đồng. Nếu gia đình thờ 3 bát hương (Thần linh ở giữa, Gia tiên bên phải, Bà cô Tổ bên trái), bát hương Thần linh phải to và kê cao hơn hai bát hương còn lại.",
      "- 5. Mâm bồng & Ngai chén: Mâm ngũ quả đặt phía trước bát hương. Ngai 3 chén hoặc 5 chén nước đặt ở mép ngoài cùng bàn thờ.",
      "## PHẦN 5: QUY TRÌNH 7 BƯỚC ĐÚC ĐỒNG THỦ CÔNG MỸ NGHỆ TẠI XƯỞNG LỘC NAM",
      "- Bước 1: Tạo mẫu đất sét định hình tỷ lệ cân đối giữa bầu đỉnh, nắp nghê và chân lân.",
      "- Bước 2: Dùng đất phù sa sông Đáy trộn trấu và giấy dó làm khuôn đúc âm dương bản, sau đó sấy nung khuôn ở 700°C liên tục 3 ngày đêm.",
      "- Bước 3: Nấu đồng đỏ nguyên chất cùng kim khí quý trong lò nung đạt nhiệt độ trên 1.200°C.",
      "- Bước 4: Rót đồng sôi đỏ rực vào khuôn đều tay, đảm bảo dòng đồng chảy liền mạch không bị rỗ bọt khí.",
      "- Bước 5: Dỡ khuôn đất sau khi đồng nguội hoàn toàn, tiến hành làm sạch cốt đồng thô nguyên khối.",
      "- Bước 6: Nghệ nhân dùng đục thép chạm khắc tay từng đường vảy rồng, chữ Hán mạ vàng, tỉa tót đuôi hạc sắc sảo từng milimet.",
      "- Bước 7: Làm màu mắt cua, hun rêu giả cổ hoặc mạ vàng 24K, cuối cùng phủ lớp sơn bóng nano 2K bảo vệ chống oxy hóa tuyệt đối.",
      "## PHẦN 6: BẢNG BÁO GIÁ BỘ ĐỒ THỜ BẰNG ĐỒNG LỘC NAM MỚI NHẤT 2026 (GIÁ GỐC TẬN XƯỞNG)",
      "- Bộ Ngũ Sự Đồng Vàng Thau 50cm - 60cm: Từ 8.500.000đ – 12.500.000đ (Bảo hành 10 năm).",
      "- Bộ Ngũ Sự Đồng Vàng Hun Rêu Cổ 60cm: Từ 11.000.000đ – 14.500.000đ (Bảo hành 15 năm).",
      "- Bộ Ngũ Sự Đồng Đỏ Nguyên Khối 60cm (nặng ~30kg): Từ 18.500.000đ – 24.000.000đ (Bảo hành 20 năm).",
      "- Bộ Ngũ Sự Đồng Cát-Tút Vỏ Đạn 60cm - 65cm: Từ 26.000.000đ – 35.000.000đ (Bảo hành trọn đời).",
      "- Bộ Ngũ Sự Khảm Tam Khí Bạc 9999 Cao Cấp: Từ 28.000.000đ – 38.000.000đ (Bảo hành trọn đời).",
      "- Bộ Ngũ Sự Mạ Vàng Ròng 24K / Dát Vàng 9999: Từ 45.000.000đ – 75.000.000đ (Bảo hành trọn đời có chứng thư giám định vàng).",
      "> Lưu ý: Giá trên đã bao gồm chi phí đóng kiện gỗ và cước vận chuyển tận nhà trên toàn quốc. Khách hàng kiểm tra đúng mẫu mã, cân nặng mới thanh toán.",
      "## PHẦN 7: CÂU HỎI THƯỜNG GẶP KHI MUA ĐỒ THỜ BẰNG ĐỒNG (FAQ)",
      "### Đồ thờ bằng đồng của Lộc Nam có bị xỉn đen hay hoen gỉ không?",
      "Sản phẩm của Đồ Đồng Lộc Nam sau khi hoàn thiện đều được xử lý bề mặt kỹ lưỡng và phủ lớp bóng 2K nano chuyên dụng ngăn chặn hoàn toàn không khí tiếp xúc với bề mặt kim loại. Sản phẩm giữ độ sáng bóng từ 15 đến trên 30 năm, chỉ cần lau bằng khăn khô mềm định kỳ.",
      "### Khách hàng ở xa (Hà Nội, Đà Nẵng, TP.HCM) đặt mua thì nhận hàng thế nào?",
      "Xưởng Lộc Nam có mạng lưới giao hàng chuyên nghiệp bằng xe tải hoặc bưu điện hỏa tốc tận nhà. Mọi đơn hàng đều được bọc xốp bóng khí và đóng thùng gỗ kín. Khi hàng tới nơi, quý khách được quyền mở kiện hàng kiểm tra kỹ lưỡng hoa văn, cân nặng trước khi thanh toán tiền.",
      "### Xưởng có nhận đúc đồ thờ, tượng đồng theo yêu cầu riêng không?",
      "Có. Chúng tôi chuyên nhận đúc đỉnh đồng cỡ đại cho nhà thờ họ, đúc tượng chân dung truyền thần cụ ông/cụ bà giống ảnh 99%, đúc chuông đồng đại hồng chung và dát vàng 9999 theo yêu cầu riêng.",
      "## PHẦN 8: LIÊN HỆ ĐẶT HÀNG TẬN XƯỞNG ĐÚC ĐỒNG LỘC NAM",
      "- Trụ sở xưởng đúc chính: Cụm Làng Nghề Đúc Đồng Truyền Thống, Huyện Ý Yên, Tỉnh Nam Định.",
      "- Website chính thức: https://www.quatanglocnam.com",
      "- Hotline / Zalo tư vấn nghệ nhân 24/7: 0846 699 997 – 0836 122 222",
      "- Email tiếp nhận bản vẽ: dodonglocnam1102@gmail.com",
      "- Thời gian mở cửa đón tiếp khách: 07:30 – 21:30 tất cả các ngày trong tuần."
    ]
  },
  {
    slug: "bi-quyet-chon-do-tho-cung-bang-dong-nam-dinh",
    title: "Bí Quyết Chọn Đồ Thờ Cúng Bằng Đồng Nam Định Chuẩn Phong Thủy Gia Tiên",
    summary: "Hướng dẫn chi tiết từ nghệ nhân Đồ Đồng Lộc Nam về cách chọn bộ đỉnh đồng, lư hương, hạc thờ theo thước Lỗ Ban và tuổi mệnh gia chủ.",
    category: "BẠN CÓ BIẾT",
    date: "27/08/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/do-tho-cung.jpg",
    readTime: "5 phút đọc",
    keywords: ["đồ đồng nam định", "đồ đồng đẹp", "đồ thờ cúng bằng đồng", "đồ đồng lộc nam", "đỉnh đồng ý yên"],
    content: [
      "Trong văn hóa tâm linh người Việt, không gian thờ cúng gia tiên luôn là nơi linh thiêng, tôn nghiêm nhất của ngôi nhà. Việc lựa chọn đồ thờ cúng bằng đồng chuẩn xuất xứ từ làng nghề đúc đồng truyền thống Ý Yên, Nam Định không chỉ mang lại vẻ đẹp uy nghiêm mà còn tích tụ vượng khí, tài lộc cho gia đạo.",
      "### 1. Tại sao nên chọn đồ đồng Nam Định?",
      "Làng nghề đúc đồng Ý Yên – Nam Định với lịch sử hơn 900 năm được mệnh danh là cái nôi của nghệ thuật đúc đồng Việt Nam. Đồ Đồng Lộc Nam tại Nam Định sử dụng 100% phôi đồng đỏ, đồng catut thanh khiết, được nung chảy ở nhiệt độ trên 1200 độ C và đúc thủ công nguyên khối.",
      "Ưu điểm nổi bật của đồ đồng Nam Định:",
      "- Độ bền vĩnh cửu: Đồng thanh khiết không bị giòn, nứt hay bong tróc theo thời gian.",
      "- Hoa văn chạm khắc tinh xảo: Từng họa tiết Rồng chầu mặt nguyệt, Hoa sòi, Nghê vờn cầu được nghệ nhân chạm khắc tay sắc nét.",
      "- Màu sắc cổ kính, sang trọng: Được hun màu giả cổ hoặc mạ vàng 24k, dát vàng 9999 cao cấp.",
      "### 2. Chọn kích thước bộ đồ thờ theo thước Lỗ Ban",
      "Kích thước bộ đỉnh đồng (bộ tam sự, ngũ sự) cần tương xứng với kích thước bàn thờ gia tiên:",
      "- Bàn thờ dài 1m27 – 1m55: Phù hợp với bộ đỉnh đồng cao 45cm – 50cm.",
      "- Bàn thờ dài 1m75 – 1m97: Phù hợp với bộ ngũ sự cao 60cm – 65cm.",
      "- Bàn thờ dài trên 2m17 (từ đường, nhà thờ họ): Phù hợp với bộ ngũ sự cao 70cm trở lên.",
      "### 3. Địa chỉ mua đồ đồng đẹp uy tín",
      "Xưởng đúc Đồ Đồng Lộc Nam tự hào là đơn vị trực tiếp sản xuất và phân phối các mẫu đồ đồng đẹp, đồ thờ cúng cao cấp không qua trung gian. Quý khách hàng được kiểm tra hàng trước khi thanh toán và nhận phiếu bảo hành trọn đời chất lượng đồng."
    ]
  },
  {
    slug: "quy-trinh-duc-tuong-dong-chan-dung-truyen-than",
    title: "Quy Trình Đúc Đồng Chân Dung Truyền Thần Giống Thật 100% Của Xưởng Lộc Nam",
    summary: "Khám phá kỹ thuật đúc tượng chân dung ông bà, cha mẹ, danh nhân bằng đồng đỏ nguyên khối đạt độ giống và thần thái tới 99.9%.",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "26/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/4.jpg",
    readTime: "7 phút đọc",
    keywords: ["đúc đồng chân dung", "đúc tượng chân dung", "đồ đồng lộc nam", "tượng đồng nam định", "đúc tượng truyền thần"],
    content: [
      "Dịch vụ đúc đồng chân dung truyền thần để báo hiếu cha mẹ, tưởng nhớ tổ tiên hoặc tôn vinh các bậc tiền nhân, danh nhân lịch sử đang là xu hướng được nhiều gia đình và tổ chức lựa chọn.",
      "Tuy nhiên, đúc tượng chân dung là phân khúc khó nhất trong nghệ thuật đúc đồng vì đòi hỏi không chỉ tay nghề kỹ thuật mà còn phải truyền tải được cái thần, nét mặt và thần thái sống động của nhân vật.",
      "### Quy trình 5 bước đúc tượng chân dung tại Đồ Đồng Lộc Nam:",
      "1. Tạo mẫu đất sét (Khâu quan trọng nhất): Dựa trên hình ảnh chụp đa góc độ của nhân vật, điêu khắc gia đắp mẫu đất sét tỷ lệ 1:1. Khách hàng sẽ được xem trực tiếp hoặc duyệt qua video/ảnh để chỉnh sửa từng đường nét mắt, mũi, nụ cười đến khi ưng ý 100%.",
      "2. Làm khuôn thạch cao & khuôn composite: Chuyển mẫu đất sang khuôn âm bản chịu nhiệt đặc biệt để giữ nguyên từng chi tiết vi mô.",
      "3. Luyện đồng & Nấu đồng đỏ: Sử dụng đồng đỏ thanh khiết (đồng dây điện loại 1), pha tỷ lệ thiếc và kẽm chuẩn xác để dòng chảy đồng mịn và đều.",
      "4. Rót đồng vào khuôn: Nghệ nhân canh nhiệt độ rót đều tay, hạn chế tối đa bọt khí.",
      "5. Làm nguội, chạm tỉa & mạ dát vàng: Dũa gọt, chạm trổ từng sợi tóc, nếp nhăn và hoàn thiện bề mặt (phủ bóng nano, mạ vàng 24k hoặc dát vàng 9999).",
      "### Cam kết chất lượng từ Đồ Đồng Lộc Nam:",
      "Tất cả các sản phẩm đúc đồng chân dung tại xưởng Lộc Nam đều được bảo đảm độ giống thực tế, đúc liền khối vững chắc trường tồn cùng thời gian."
    ]
  },
  {
    slug: "top-mau-do-dong-dep-tinh-xao-nhat-nam-nay",
    title: "Top Các Mẫu Đồ Đồng Đẹp, Tinh Xảo Được Ưa Chuộng Nhất Năm Nay",
    summary: "Tổng hợp các kiệt tác đồ đồng mỹ nghệ: tượng Bác Hồ, tượng Trần Hưng Đạo, đỉnh đồng khảm ngũ sắc thất lân và tranh đồng mạ vàng.",
    category: "BẠN CÓ BIẾT",
    date: "25/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/do-tho-day-du-ma-vang.jpg",
    readTime: "4 phút đọc",
    keywords: ["đồ đồng đẹp", "đồ đồng nam định", "đồ đồng lộc nam", "tượng đồng phong thủy", "bộ ngũ sự khảm ngũ sắc"],
    content: [
      "Thị trường mỹ nghệ ngày càng phát triển với nhiều sản phẩm đồng đúc cao cấp. Dưới đây là danh sách những mẫu đồ đồng đẹp được các gia chủ, doanh nhân và nhà sưu tầm săn đón nhiều nhất hiện nay:",
      "### 1. Bộ Ngũ Sự Khảm Ngũ Sắc Thất Lân Vờn Cầu",
      "Đỉnh đồng thất lân kết hợp đôi chân nến và đôi hạc thờ được khảm 5 kim loại quý: Vàng 9999, Bạc trắng, Đồng đỏ, Đồng xanh và Đồng đen. Từng đường khảm chìm sâu vào phôi đồng tạo nên hoa văn sống động và uy nghiêm trên ban thờ.",
      "### 2. Tượng Trần Quốc Tuấn Đồng Catut Cao Cấp",
      "Bức tượng Quốc Công Tiết Chế Hưng Đạo Đại Vương cầm hịch tướng sĩ đúc từ vỏ đạn quân sự (đồng catut) màu vàng ánh kim rực rỡ, mang năng lượng trấn trạch, trừ tà và đem lại uy quyền cho gia chủ.",
      "### 3. Tượng Bác Hồ Ngồi Ghế Mây Mạ Vàng 24K",
      "Tác phẩm tượng đồng chân dung Bác Hồ với thần thái ung dung, hiền từ là quà tặng ngoại giao và vật phẩm trang trọng hàng đầu tại các cơ quan, hội trường và phòng lưu niệm.",
      "### 4. Tranh Đồng Vinh Hoa Phú Quý 2m3 Mạ Vàng Dát Bạc",
      "Bức tranh phong cảnh cây tùng, chim hạc, hoa cúc, cuốn thư mang ý nghĩa cầu chúc tài lộc, gia đình sung túc, con cháu vinh hiển."
    ]
  },
  {
    slug: "y-nghia-phong-thuy-trong-dong-dong-son",
    title: "Ý Nghĩa Phong Thủy Trống Đồng Đông Sơn Trong Phòng Khách & Cơ Quan",
    summary: "Tại sao các doanh nhân thành đạt và cơ quan nhà nước luôn đặt trống đồng Đông Sơn tại vị trí trang trọng nhất?",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "24/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/qua-trong-dong-dong-son.jpg",
    readTime: "6 phút đọc",
    keywords: ["trống đồng đông sơn", "đồ đồng đẹp", "đồ đồng nam định", "quà tặng trống đồng", "đồ đồng lộc nam"],
    content: [
      "Trống đồng Đông Sơn không chỉ là bảo vật biểu tượng cho nền văn minh sông Hồng mà còn là vật phẩm phong thủy mang quyền năng trấn trạch và thu hút linh khí cực mạnh.",
      "### 1. Ý nghĩa biểu tượng của mặt trống đồng",
      "- Tâm trống (Mặt trời): Đại diện cho nguồn sống vô tận, ánh sáng xua tan tà khí và bóng tối, soi đường chỉ lối cho gia chủ hanh thông trong sự nghiệp.",
      "- Hình tượng chim Lạc bay ngược chiều kim đồng hồ: Tượng trưng cho dòng chảy thời gian và cội nguồn bất diệt của dân tộc Việt.",
      "- Cảnh sinh hoạt giã gạo, múa hát, chèo thuyền: Thể hiện sự ấm no, đoàn kết và sinh sôi nảy nở của tài lộc.",
      "### 2. Vị trí đặt trống đồng hợp phong thủy",
      "- Phòng khách: Đặt trên đôn gỗ cao 60cm – 80cm tại hướng Tây Bắc hoặc chính Bắc để kích hoạt tài vận.",
      "- Phòng làm việc / Phòng giám đốc: Đặt sau lưng bàn làm việc hoặc trên kệ tủ tài liệu tạo điểm tựa vững chắc, nâng cao uy quyền.",
      "- Phòng họp & Hội trường: Đặt mô hình trống đồng lớn ở trung tâm mang lại sự trang nghiêm và thịnh vượng bền lâu."
    ]
  },
  {
    slug: "cach-phan-biet-do-dong-that-va-dong-pha-tap-chat",
    title: "5 Cách Phân Biệt Đồ Đồng Thật và Đồng Pha Tạp Chất Đơn Giản Nhất",
    summary: "Cẩm nang bỏ túi giúp người mua không bị mắc bẫy đồng Đài Loan mạ màu hoặc đồng pha chì kém chất lượng.",
    category: "BẠN CÓ BIẾT",
    date: "23/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/artisan-foundry.jpg",
    readTime: "5 phút đọc",
    keywords: ["phân biệt đồ đồng", "đồ đồng nam định", "đồ đồng đẹp", "đồ đồng lộc nam", "mua đồ đồng uy tín"],
    content: [
      "Hiện nay trên thị trường có nhiều loại đồ đồng công nghiệp mạ xi mỏng hoặc đồng pha nhiều chì, kẽm chỉ sau 6 tháng đến 1 năm là bị bong tróc, xỉn đen không thể phục hồi.",
      "Dưới đây là 5 mẹo từ nghệ nhân xưởng Đồ Đồng Lộc Nam giúp bạn nhận biết ngay đồng thật chuẩn chất lượng:",
      "### 1. Kiểm tra bằng trọng lượng",
      "Đồ đồng thủ công Nam Định đúc bằng đồng thanh khiết thành dày bản nên cầm rất đầm tay, nặng hơn đáng kể so với đồ đồng dập máy công nghiệp mỏng rỗng ruột.",
      "### 2. Kiểm tra bằng âm thanh (tiếng chuông)",
      "Khi dùng thanh kim loại gõ nhẹ vào thân đỉnh đồng hoặc tượng đồng thật, âm thanh phát ra sẽ vang trầm, ấm và ngân dài. Trong khi đó đồng pha tạp chất hoặc đồng mỏng sẽ kêu cạch cạch đanh ngắn.",
      "### 3. Kiểm tra bằng lửa",
      "Đồng thật nguyên chất có nhiệt độ nóng chảy rất cao (> 1000°C). Khi hơ ngọn lửa gas vào bề mặt, đồng xịn không hề biến đổi màu hay bong tróc, chỉ cần lau nhẹ tàn khói là sáng bóng như mới.",
      "### 4. Kiểm tra đường nét hoa văn",
      "Đồ đồng thủ công mỹ nghệ có hoa văn chạm trổ thủ công mềm mại, sắc sảo từng milimet, không có vết ráp thô kệch hay ba-via lởm chởm như hàng đúc máy giá rẻ.",
      "### 5. Chọn cơ sở có cam kết bảo hành",
      "Hãy mua tại các xưởng đúc trực tiếp có thương hiệu như Đồ Đồng Lộc Nam – có địa chỉ xưởng rõ ràng tại làng nghề đúc đồng Ý Yên Nam Định và cam kết bảo hành trọn đời bằng văn bản."
    ]
  }
];
