export interface Article {
  slug: string;
  title: string;
  summary: string;
  category: string;
  date: string;
  author: string;
  image: string;
  readTime: string;
  keywords: string[];
  content: string[];
}

export const articlesData: Article[] = [
  {
    slug: "nghe-nhan-duong-ba-tien",
    title: "Nghệ Nhân Dương Bá Tiến - 40 Năm Gìn Giữ Tinh Hoa Nghề Đúc Đồng Lộc Nam",
    summary: "Tìm hiểu về nghệ nhân Dương Bá Tiến - Bàn tay vàng với 40 năm cống hiến cho nghề đúc đồng truyền thống tại làng nghề Ý Yên, Nam Định. Gìn giữ tinh hoa nghề xưa và đưa thương hiệu Lộc Nam vươn tầm quốc gia.",
    category: "NGHỆ NHÂN & LÀNG NGHỀ",
    date: "15/09/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/le-trao-bang-vinh-danh-cup-ban-tay-vang-loc-nam.png",
    readTime: "8 phút đọc",
    keywords: [
      "nghệ nhân đúc đồng",
      "dương bá tiến",
      "nghệ nhân bàn tay vàng",
      "đúc đồng lộc nam",
      "đồ thờ bằng đồng",
      "nghề đúc đồng truyền thống",
      "làng nghề ý yên",
      "tranh đồng nam định",
      "đồ đồng thủ công",
      "công ty đúc đồng",
      "ý yên nam định",
      "làng nghề nam định",
      "nghệ nhân nam định",
      "đúc đồng ý yên"
    ],
    content: [
      "Giữa cái nôi của làng nghề đúc đồng Vạn Điểm – Ý Yên, Nam Định với lịch sử hơn 900 năm hưng thịnh, cái tên Nghệ nhân Dương Bá Tiến – người sáng lập Công ty TNHH Cơ Khí Đúc Lộc Nam đã trở thành biểu tượng cho sự bền bỉ, tài hoa và lòng tận tụy gìn giữ ngọn lửa nghề truyền thống. Với hơn bốn thập kỷ miệt mài bên khuôn đất, lò nung, người nghệ nhân mang danh hiệu 'Bàn Tay Vàng' không chỉ kế thừa tinh hoa của tiền nhân mà còn nâng tầm từng thỏi đồng thô ráp trở thành những kiệt tác đồ thờ, tượng đồng và tranh đồng mỹ nghệ mang hồn cốt dân tộc, vang danh khắp mọi miền Tổ quốc và vươn ra bạn bè quốc tế.",
      "![Nghệ nhân Dương Bá Tiến vinh dự nhận Cúp Bàn Tay Vàng trong Chương trình Vinh danh Thương hiệu truyền thống, Gia truyền Làng nghề Việt](/images/locnam_real/le-trao-bang-vinh-danh-cup-ban-tay-vang-loc-nam.png)",
      "## Hành Trình 40 Năm Cống Hiến Cho Nghề Đúc Đồng",
      "Sinh ra và lớn lên trên mảnh đất địa linh nhân kiệt Ý Yên, tuổi thơ của nghệ nhân Dương Bá Tiến đã gắn liền với tiếng búa gõ lách cách, mùi đất sét làm khuôn nồng ấm và ánh lửa bập bùng từ những mẻ đồng sôi sục. Được các bậc tiền bối trong dòng tộc truyền trao ngọn lửa nhiệt huyết từ thuở niên thiếu, ông xem nghề đúc đồng thủ công không đơn thuần là kế sinh nhai, mà là nghiệp duyên cả đời phải phụng sự.",
      "Những ngày đầu học nghề là chuỗi ngày gian nan thử thách bản lĩnh. Thời điểm đó, kỹ thuật đúc đồng hoàn toàn dựa vào kinh nghiệm thủ công truyền miệng: từ khâu chọn đất sét dẻo quánh pha trấu mục, căn chỉnh nhiệt độ lò nung bằng mắt thường ở ngưỡng trên 1.200°C, cho đến khoảnh khắc rót đồng đòi hỏi sự chuẩn xác tuyệt đối từng giây. Đã có những mẻ đồng hỏng, những pho tượng rỗ bề mặt hay nứt vỡ khuôn ép ông phải làm lại từ đầu. Nhưng chính từ những thử thách khắc nghiệt ấy, ý chí sắt đá và đôi bàn tay tài hoa của người con đất Nam Định ngày càng được tôi luyện sắc sảo.",
      "![Bằng chứng nhận hoàn thành khóa đào tạo thợ cả điêu khắc thủ công mỹ nghệ quốc tế AusAID/HASMEA trao tặng Dương Bá Tiến](/images/locnam_real/chung-chi-dao-tao-dieu-khac-duong-ba-tien.png)",
      "Hơn 40 năm lao động sáng tạo không ngơi nghỉ, nghệ nhân Dương Bá Tiến đã đưa tinh hoa nghề cổ truyền bước qua thăng trầm thời đại, khẳng định chỗ đứng vững chắc của Đúc đồng Lộc Nam trên bản đồ thủ công mỹ nghệ Việt Nam.",
      "## Danh Hiệu 'Nghệ Nhân Bàn Tay Vàng' - Niềm Tự Hào Của Làng Nghề",
      "Sự tận tụy chí công vô tư và trình độ kỹ nghệ xuất sắc của ông đã được Nhà nước và các hiệp hội làng nghề ghi nhận bằng danh hiệu cao quý: Nghệ nhân Bàn Tay Vàng. Đây không chỉ là một danh xưng danh dự, mà là sự tôn vinh xứng đáng cho một đời người cống hiến trọn vẹn vì sự nghiệp bảo tồn di sản văn hóa phi vật thể của dân tộc.",
      "Để được phong tặng danh hiệu 'Bàn Tay Vàng', người nghệ nhân phải trải qua quá trình thẩm định nghiêm ngặt về tài năng sáng tạo, số lượng tác phẩm tiêu biểu có giá trị nghệ thuật cao và những đóng góp tích cực cho cộng đồng làng nghề Ý Yên – Nam Định. Danh hiệu cúp vàng và bằng chứng nhận là bảo chứng thép cho tài năng chạm khắc tinh xảo, khả năng truyền thần vào từng pho tượng Phật, tượng danh nhân, và các bộ đại tự câu đối trang nghiêm.",
      "![Bằng chứng nhận Cúp Bàn Tay Vàng trao tặng cho Ông Dương Bá Tiến - Công ty TNHH Cơ Khí Đúc Lộc Nam](/images/locnam_real/bang-chung-nhan-cup-ban-tay-vang-duong-ba-tien.png)",
      "![Cận cảnh Cúp Bàn Tay Vàng danh giá mạ vàng trao tặng Nghệ nhân Dương Bá Tiến tại Ý Yên Nam Định](/images/locnam_real/cup-ban-tay-vang-duong-ba-tien-loc-nam.png)",
      "Đối với bà con vùng đất đúc đồng Ý Yên, nghệ nhân Dương Bá Tiến chính là niềm tự hào, là tấm gương sáng truyền cảm hứng cho lớp thợ trẻ noi theo để giữ trọn ngọn lửa cha ông để lại.",
      "## Công Ty TNHH Cơ Khí Đúc Lộc Nam - Nơi Hội Tụ Tinh Hoa",
      "Từ nền tảng xưởng đúc gia truyền, nghệ nhân Dương Bá Tiến đã chính thức thành lập Công ty TNHH Cơ Khí Đúc Lộc Nam, tạo nên bước ngoặt chuyển mình mạnh mẽ từ mô hình sản xuất nhỏ lẻ sang quy mô doanh nghiệp chuyên nghiệp và bài bản.",
      "Lộc Nam quy tụ hệ thống nhà xưởng sản xuất quy mô lớn tại Ý Yên, được trang bị đầy đủ từ hệ thống lò nấu đồng dung tích lớn, khu tạo khuôn chuẩn chỉ cho tới phòng mạ – thếp vàng khép kín. Dưới sự dẫn dắt trực tiếp của nghệ nhân Dương Bá Tiến, công ty quy tụ đội ngũ gần 100 nghệ nhân và thợ thủ công lành nghề bậc cao.",
      "Mọi sản phẩm xuất xưởng đều tuân thủ nghiêm ngặt quy trình thủ công khép kín 7 bước: tạo mẫu - làm khuôn đất - nung khuôn - nấu đồng nguyên chất - rót đồng - sửa nguội chạm ám - đánh bóng hoàn thiện và phủ bảo vệ. Sự kết hợp giữa kỹ thuật gia truyền và kỷ luật quản lý hiện đại giúp Đồ Đồng Lộc Nam đáp ứng hoàn hảo mọi đơn hàng từ các bộ đồ thờ gia tiên tinh xảo đến các đại công trình tượng đài tầm cỡ quốc gia.",
      "## Sản Phẩm Đồ Đồng Lộc Nam - Tiếng Vang Khắp Cả Nước",
      "Trải qua nhiều thập kỷ khẳng định thương hiệu, các sản phẩm của Lộc Nam đã hiện diện trang trọng trong hàng vạn gia đình, đền miếu, từ đường và các công trình văn hóa tâm linh trọng điểm:",
      "- Đồ thờ bằng đồng cao cấp: Bộ tam sự, ngũ sự, đỉnh đồng, hạc ngự long quy, bát hương, mâm bồng đúc bằng đồng đỏ, đồng vàng thanh khiết; khảm tam khí, khảm ngũ sắc tinh xảo với độ bền truyền đời.",
      "- Tượng đồng mỹ thuật & danh nhân: Tượng Chủ tịch Hồ Chí Minh, tượng Đức Thánh Trần, tượng Phật Thích Ca, Quan Âm, tượng chân dung người thật đạt độ thần thái truyền thần sống động trên 95%.",
      "- Tranh đồng & Trống đồng phong thủy: Tranh Mã Đáo Thành Công, Thuận Buồm Xuôi Gió, Trống đồng Đông Sơn, Ngọc Lũ dát vàng 24K sang trọng, tượng trưng cho vượng khí và phú quý.",
      "Mỗi sản phẩm mang thương hiệu Lộc Nam luôn khẳng định uy tín bằng ba yếu tố cốt lõi: Đồng nguyên chất không pha tạp - Hoa văn chạm khắc thủ công sắc sảo - Bảo hành độ bền trọn đời. Nhờ đó, sản phẩm không chỉ được săn đón tại Hà Nội, TP. Hồ Chí Minh, Đà Nẵng mà còn được kiều bào tại Mỹ, Pháp, Úc, Nhật Bản trân trọng đặt hàng mang ra nước ngoài.",
      "![Bộ đồ thờ bằng đồng đỏ khảm tam khí cao cấp chế tác thủ công bởi Đồ Đồng Lộc Nam](/images/locnam_real/locnam_bo_do_tho.jpg)",
      "## Giá Trị Cốt Lõi - Tâm Huyết Của Nghệ Nhân",
      "Với nghệ nhân Dương Bá Tiến, 'Chữ Tâm quý hơn chữ Vàng'. Mỗi món đồ thờ cúng bằng đồng khi đặt lên ban thờ gia tiên hay nơi cửa thiền linh thiêng đều chứa đựng sự tôn kính của con cháu đối với nguồn cội. Do đó, người thợ đúc đồng không bao giờ được phép làm ẩu, bớt xén nguyên liệu hay pha tạp hợp kim độc hại.",
      "> 'Nghề đúc đồng cha ông truyền lại cho mình, mình không chỉ giữ cho riêng mình mà phải làm cho nó rạng danh. Khách hàng tìm đến Lộc Nam là gửi gắm niềm tin tâm linh và lòng hiếu kính, mình phải đem hết cái tâm, cái tài đúc nên những pho tượng, món đồ thờ hoàn mỹ nhất.' — Nghệ nhân Dương Bá Tiến chia sẻ.",
      "Trước làn sóng công nghiệp hóa và sản phẩm đồng đúc máy dập khuôn giá rẻ tràn lan, Đồ Đồng Lộc Nam kiên định con đường chế tác thủ công mỹ nghệ đỉnh cao. Đó là cách nghệ nhân Dương Bá Tiến và tập thể Lộc Nam giữ gìn căn cốt văn hóa cội nguồn của người Việt cho muôn đời sau.",
      "## Thông Tin Liên Hệ Đồ Đồng Lộc Nam",
      "- Công ty TNHH Cơ Khí Đúc Lộc Nam",
      "- Xưởng đúc chính: Làng nghề đúc đồng Ý Yên, Huyện Ý Yên, Tỉnh Nam Định",
      "- Showroom trưng bày: Thị trấn Lâm, Ý Yên, Nam Định",
      "- Hotline tư vấn trực tiếp nghệ nhân: 0336.222.222 – 0836.122.222",
      "- Email: contact@quatanglocnam.com",
      "- Website chính thức: https://www.quatanglocnam.com"
    ]
  },
  {
    slug: "xuong-san-xuat-duc-dong-loc-nam",
    title: "Xưởng Đúc Đồng Lộc Nam - Hệ Thống 7 Phân Xưởng Chuyên Sâu Khép Kín",
    summary: "Khám phá xưởng đúc đồng Lộc Nam tại Ý Yên Nam Định: 3 trụ sở sản xuất quy mô lớn, 7 phân xưởng chức năng khép kín, gần 100 thợ thủ công lành nghề và công nghệ mạ dát vàng 9999 đỉnh cao.",
    category: "XƯỞNG ĐÚC LỘC NAM",
    date: "15/09/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/xuong_duc.jpg",
    readTime: "9 phút đọc",
    keywords: [
      "xưởng đúc đồng",
      "sản xuất đồ đồng",
      "xưởng đồng lộc nam",
      "đúc đồng trực tiếp",
      "quy trình đúc đồng",
      "mạ vàng 9999",
      "thợ đúc đồng",
      "xưởng đồng nam định",
      "đúc đồng ý yên"
    ],
    content: [
      "Trong bối cảnh thị trường thủ công mỹ nghệ xuất hiện nhiều đơn vị thương mại trung gian phân phối hàng gia công trôi nổi, Xưởng đúc đồng Lộc Nam tự hào khẳng định vị thế xưởng sản xuất trực tiếp hàng đầu tại làng nghề truyền thống Ý Yên, Nam Định. Với hệ thống 3 cơ sở sản xuất quy mô bề thế, đội ngũ gần 100 công nhân viên kỹ thuật cao và dây chuyền 7 phân xưởng chức năng riêng biệt, Lộc Nam tự chủ 100% quy trình sản xuất từ khâu đắp mẫu đất sét ban đầu đến khi xuất xưởng những tuyệt tác mạ vàng 9999 hoàn mỹ.",
      "![Toàn cảnh không gian sản xuất quy mô lớn tại hệ thống xưởng đúc đồng Lộc Nam Ý Yên Nam Định](/images/xuong_duc.jpg)",
      "## Quy Mô Xưởng Sản Xuất Hiện Đại Tại Cái Nôi Ý Yên",
      "Tọa lạc tại vùng lõi của làng nghề đúc đồng nức tiếng Nam Định, cơ ngơi sản xuất của Công ty TNHH Cơ Khí Đúc Lộc Nam được đầu tư bài bản trên diện tích hàng trăm mét vuông, bao gồm 3 trụ sở xưởng sản xuất đồng bộ và hệ thống cửa hàng showroom trưng bày sản phẩm khang trang.",
      "Xưởng được trang bị hệ thống giàn cẩu trục chịu tải hàng chục tấn, các cụm lò luyện đồng công suất lớn, máy nén khí, máy cắt Plasma cùng hệ thống xử lý khói bụi đảm bảo an toàn lao động và bảo vệ môi trường làng nghề. Quy mô vững chắc cùng sự quy tụ của gần 100 công nhân viên có tay nghề bậc cao chính là năng lực cốt lõi giúp Lộc Nam sẵn sàng đảm đương những dự án đúc tượng đài vĩ mô hàng chục tấn lẫn các đơn hàng quà tặng doanh nghiệp hàng nghìn sản phẩm theo tiến độ chuẩn xác.",
      "## 7 Phân Xưởng Chuyên Biệt - Quy Trình Sản Xuất Hoàn Hảo Từ A Đến Z",
      "Để mỗi sản phẩm đồ thờ, tranh đồng hay tượng đồng đạt đến độ tinh xảo đỉnh cao, quy trình chế tác tại Lộc Nam được tổ chức khoa học qua 7 phân xưởng chuyên biệt:",
      "### Phân Xưởng 1: Khu Vực Điêu Khắc & Làm Mẫu Tạo Hình",
      "Mọi kiệt tác đều khởi nguồn từ chiếc phôi mẫu chuẩn xác. Tại phân xưởng làm mẫu, các nghệ nhân điêu khắc hàng đầu trực tiếp nhào nặn đất sét hoặc đục đẽo thạch cao theo tỉ lệ nhân trắc học và đường nét cổ truyền. Từng khóe mắt, nụ cười trên tượng chân dung hay từng vảy rồng trên đỉnh đồng đều được gọt giũa tỉ mẩn, bảo đảm độ sắc nét và cái hồn sống động trước khi đem chuyển thể sang phôi đúc.",
      "### Phân Xưởng 2: Khu Vực Tạo Khuôn Đất Thủ Công Truyền Thống",
      "Làm khuôn là khâu then chốt quyết định sự thành bại của mẻ đúc. Phân xưởng khuôn sử dụng loại đất sét mịn được chọn lọc kỹ càng, phối trộn cùng trấu mục băm nhỏ và bột giấy bản theo tỷ lệ bí truyền nhằm tạo độ dai, xốp và khả năng chịu nhiệt cao. Khuôn gồm hai phần: khuôn âm bản (khuôn ngoài) và khuôn cốt (khuôn lõi trong). Sau khi đắp khuôn, các khối khuôn được đưa vào buồng sấy khô kiệt bằng than củi liên tục nhiều ngày đêm để loại bỏ hoàn toàn hơi ẩm, ngăn ngừa triệt để nguy cơ nứt vỡ hay rỗ khí khi rót đồng nóng chảy.",
      "### Phân Xưởng 3: Khu Vực Đúc Đồng Thủ Công Mỹ Nghệ",
      "Đây là trái tim rực lửa của xưởng Lộc Nam. Nơi đây bố trí các lò nung truyền thống được duy trì ở nhiệt độ cực đại trên 1.200°C. Nguyên liệu đưa vào lò là đồng đỏ thanh khiết, đồng vàng (thau) nguyên chất cùng các hợp chất dẫn dòng được tính toán tỉ mỉ. Khi mẻ đồng chuyển sang màu đỏ rực trong suốt, các nghệ nhân cả đời kinh nghiệm sẽ phối hợp nhịp nhàng vận hành gáo múc và tiến hành rót đồng vào khuôn. Dòng đồng nóng chảy cuồn cuộn lấp đầy từng ngóc ngách hoa văn trong sự nín thở và tập trung cao độ của người thợ.",
      "![Công đoạn rót đồng sôi đỏ rực ở nhiệt độ trên 1200 độ C vào khuôn đúc thủ công](/images/artisan-foundry.jpg)",
      "### Phân Xưởng 4: Khu Vực Đúc Đồng Công Nghiệp & Khuôn Mẫu Cháy Hiện Đại",
      "Bên cạnh phương pháp đúc thủ công cho các sản phẩm đơn chiếc, Lộc Nam tiên phong ứng dụng công nghệ đúc khuôn mẫu cháy và máy móc hỗ trợ đúc áp lực cao. Phân xưởng này chuyên trách gia công hàng loạt các dòng sản phẩm quà tặng hội nghị, biểu trưng đại hội, linh vật phong thủy với độ đồng đều kích thước tuyệt đối đến từng milimet, bề mặt mịn màng và năng suất vượt trội.",
      "### Phân Xưởng 5: Khu Vực Gia Công Nguội & Chạm Khảm Tinh Xảo",
      "Sau khi dỡ khuôn và phá bỏ lớp đất bám ngoài, phôi đồng trần được chuyển về xưởng nguội. Tại đây, những người thợ chạm bậc thầy dùng búa, ve đục chuyên dụng để mài nhẵn bavia thừa, đục rãnh và tiến hành nghệ thuật khảm tam khí (bạc, đồng đỏ, đồng vàng) hoặc khảm ngũ sắc (thêm vàng 9999 và đồng xanh). Từng sợi bạc trắng, chỉ vàng 24K được nạm sâu vào thớ đồng, miết chặt phẳng lì, tạo nên những bức họa đồ lộng lẫy và sống động.",
      "### Phân Xưởng 6: Khu Vực Hoàn Thiện Bề Mặt & Tạo Màu Cổ Truyền",
      "Sản phẩm sau khi chạm khắc được đưa vào quy trình đánh bóng cơ học bằng quả phớt nỉ và bột cát chuyên dụng. Tiếp đó, thợ tạo màu sẽ áp dụng các phương pháp hun màu gia truyền để tạo nên những gam màu trầm mặc cổ kính như: màu cánh gián, màu hun đen giả cổ, màu xanh rêu phong ba hoặc màu đồng đỏ nguyên bản. Cuối cùng, toàn bộ bề mặt được phủ 2 lớp sơn bảo vệ 2K bóng mờ cao cấp, chống oxy hóa, ngăn chặn tuyệt đối tình trạng ố xanh do thời tiết nóng ẩm tại Việt Nam.",
      "### Phân Xưởng 7: Khu Vực Mạ Vàng Điện Phân & Thếp Vàng Quỳ 9999",
      "Phân xưởng khép kín đạt tiêu chuẩn cao cấp chuyên phục vụ các đơn hàng xa xỉ. Lộc Nam ứng dụng công nghệ mạ vàng điện phân nhúng bể 24K đa lớp giúp vàng bám sâu, bóng mịn không tì vết. Đối với đồ thờ cúng và tượng tâm linh, các nghệ nhân tiến hành dán thếp từng lá vàng quỳ 9999 thủ công truyền thống, mang lại sắc vàng rực rỡ, ánh kim ấm áp và linh khí tôn nghiêm trường tồn cùng thời gian.",
      "![Sản phẩm đỉnh đồng ngũ sự mạ vàng dát vàng 9999 hoàn thiện sáng bóng lộng lẫy](/images/bo-do-tho-ma-vang.jpg)",
      "## Đội Ngũ 100 Công Nhân Viên Lành Nghề & Đầy Nhiệt Huyết",
      "Tài sản lớn nhất làm nên uy tín thương hiệu Lộc Nam chính là con người. Xưởng quy tụ gần 100 công nhân viên, trong đó có hơn 20 nghệ nhân kinh nghiệm trên 20 - 30 năm tuổi nghề. Đội ngũ thợ của Lộc Nam được đào tạo bài bản từ cốt cách làng nghề, luôn làm việc với tinh thần tôn kính tâm linh và trách nhiệm cao nhất với từng nét chạm trổ. Sự kết hợp bền chặt giữa thế hệ nghệ nhân gạo cội giàu kinh nghiệm và thế hệ thợ trẻ nhiệt huyết, tinh thông công nghệ đã tạo nên sức mạnh tổng hòa vượt bậc cho xưởng.",
      "## Máy Móc Thiết Bị Hiện Đại Hỗ Trợ Đắc Lực",
      "- Hệ thống lò đúc công nghiệp công suất cao, kiểm soát nhiệt độ điện tử chính xác.",
      "- Máy mài nhẵn, máy đánh bóng bề mặt đa năng giúp bề mặt phôi đồng đạt độ nhẵn mịn lý tưởng.",
      "- Bể mạ điện phân hiện đại với hệ thống khuấy hóa chất và kiểm soát dòng điện tự động.",
      "- Thiết bị kiểm tra quang phổ kim loại, bảo đảm tỷ lệ đồng nguyên chất và tuổi vàng đạt chuẩn tuyệt đối trước khi bàn giao.",
      "## Cam Kết Chất Lượng Vàng Từ Đơn Vị Sản Xuất Trực Tiếp",
      "- Sản xuất trực tiếp tại xưởng: Không qua bất kỳ khâu trung gian thương mại nào, tiết kiệm 15 - 30% chi phí cho khách hàng.",
      "- Chuẩn chất liệu đồng: Cam kết sử dụng đồng đỏ cáp điện, đồng thau loại 1, tỷ lệ đồng trên 90 - 95%, nói không với đồng nát ve chai pha tạp chì.",
      "- Mạ vàng thật 100%: Kiểm định chất lượng tuổi vàng 24K, 9999 theo yêu cầu của khách hàng.",
      "- Bảo hành dài hạn: Bảo hành bề mặt 5 - 10 năm và cam kết độ bền chất liệu đồng vĩnh cửu truyền đời.",
      "## Liên Hệ Đặt Hàng Trực Tiếp Từ Xưởng Sản Xuất Lộc Nam",
      "- Hotline đặt hàng tận xưởng: 0336.222.222 – 0836.122.222",
      "- Xưởng sản xuất: Cụm làng nghề đúc đồng Ý Yên, Huyện Ý Yên, Tỉnh Nam Định",
      "- Website: https://www.quatanglocnam.com"
    ]
  },
  {
    slug: "cong-trinh-tieu-bieu",
    title: "Công Trình Tiêu Biểu - Lộc Nam Tự Hào Kiến Tạo Những Biểu Tượng Quốc Gia",
    summary: "Tổng hợp các đại công trình tiêu biểu của Lộc Nam: Đại tượng Bác Hồ 30 tấn Sơn La, Chùa Đồng Yên Tử, tượng Bác Hồ tại Học viện Chính trị CAND & Văn phòng Chính phủ, quà tặng nguyên thủ APEC 2017...",
    category: "DỰ ÁN & CÔNG TRÌNH",
    date: "15/09/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/du_an/tuong-bac-ho-vay-tay-chao-son-la.jpg",
    readTime: "11 phút đọc",
    keywords: [
      "công trình đúc đồng",
      "tượng chủ tịch hồ chí minh",
      "đúc tượng đài",
      "dự án đồ đồng",
      "tượng đồng cỡ lớn",
      "đúc tượng bác hồ",
      "quà tặng apec",
      "đồ thờ đền trần",
      "chùa đồng yên tử",
      "lộc nam nam định"
    ],
    content: [
      "Hơn 40 năm đồng hành cùng dòng chảy văn hóa ngàn năm của dân tộc, Công ty TNHH Cơ Khí Đúc Lộc Nam không chỉ khẳng định vị thế dẫn đầu trong chế tác đồ thờ cúng gia tiên mà còn vinh dự được Đảng, Nhà nước, các Bộ ban ngành và các tập đoàn hàng đầu tin tưởng giao trọng trách thi công hàng loạt công trình tượng đài lịch sử, di tích tâm linh và quà tặng ngoại giao cấp quốc tế. Mỗi công trình hoàn thành là một dấu mốc vàng son minh chứng cho tầm vóc, bàn tay tài hoa và năng lực thi công siêu trường siêu trọng của đội ngũ nghệ nhân Lộc Nam.",
      "![Đại tượng Chủ tịch Hồ Chí Minh vẫy tay chào tại Sơn La do Đúc Đồng Lộc Nam đúc và thi công](/images/du_an/tuong-bac-ho-vay-tay-chao-son-la.jpg)",
      "## 8 Đại Công Trình Cấp Quốc Gia Khẳng Định Bản Lĩnh Lộc Nam",
      "### 1. Vinh Dự Được Làm Việc Cùng Đồng Chí Nguyễn Thiện Nhân",
      "Trong hành trình cống hiến cho nền thủ công mỹ nghệ nước nhà, Ban lãnh đạo và nghệ nhân Lộc Nam đã có vinh dự đặc biệt được đón tiếp và trực tiếp làm việc cùng đồng chí Nguyễn Thiện Nhân (nguyên Ủy viên Bộ Chính trị, nguyên Chủ tịch Ủy ban Trung ương Mặt trận Tổ quốc Việt Nam). Sự quan tâm, động viên và những chỉ đạo sâu sát của lãnh đạo cấp cao là nguồn cổ vũ vô giá đối với tập thể nghệ nhân Lộc Nam trong việc giữ gìn và phát huy di sản làng nghề đúc đồng truyền thống Việt Nam.",
      "### 2. Tượng Chủ Tịch Hồ Chí Minh Tại Học Viện Chính Trị Công An Nhân Dân",
      "Một trong những dấu ấn thiêng liêng nhất của Lộc Nam là vinh dự được giao trọng trách đúc và thi công Tượng Chủ tịch Hồ Chí Minh an vị trang trọng tại khuôn viên Học viện Chính trị Công an Nhân dân. Đại lễ rót đồng đúc tượng đã diễn ra trọng thể nhân dịp kỷ niệm 75 năm Ngày Bác Hồ ra lời kêu gọi thi đua ái quốc và Ngày truyền thống lực lượng CAND. Pho tượng khắc họa chân dung Bác với phong thái uy nghi, hiền từ và đôi mắt sáng ngời, trở thành biểu tượng tinh thần giáo dục lý tưởng cách mạng sâu sắc cho bao thế hệ học viên sĩ quan CAND.",
      "![Lễ rót đồng và hoàn thiện tượng Bác Hồ trang nghiêm tại Học viện Chính trị Công an Nhân dân](/images/du_an_thucte/duc-tuong-bac-ho-hoc-vien-chinh-tri/duc-tuong-chu-tich-ho-chi-minh-hoc-vien-.jpg)",
      "### 3. Đài Tượng Biểu Tượng Người Công Nhân Mỏ Than - Quảng Ninh",
      "Tại vùng đất mỏ anh hùng Quảng Ninh, Đúc Đồng Lộc Nam đã được lựa chọn thi công tượng đài tôn vinh người công nhân mỏ than. Tác phẩm toát lên vẻ đẹp kiên cường, gân guốc và tinh thần quật khởi 'Kỷ luật và Đồng tâm' của những người con lao động vùng than. Tượng đài được đúc bằng hợp kim đồng đặc biệt, chịu được khí hậu ven biển khắc nghiệt, sừng sững trở thành niềm tự hào của ngành than Việt Nam.",
      "### 4. Quần Thể Tượng Nghệ Thuật Đương Đại Tại Flamingo Đại Lải Resort",
      "Vượt ra ngoài khuôn khổ các tác phẩm truyền thống, Lộc Nam đã chứng minh năng lực sáng tạo đỉnh cao qua dự án chế tác cụm tượng nghệ thuật đương đại tại khu nghỉ dưỡng 5 sao Flamingo Đại Lải (Vĩnh Phúc). Từng đường cong kim loại mượt mà, sự kết hợp tinh tế giữa nghệ thuật đúc đồng và cảnh quan thiên nhiên đã tạo nên điểm nhấn kiến trúc độc bản làm say lòng du khách trong và ngoài nước.",
      "### 5. Chế Tác & An Vị Tượng Bác Hồ Tại Văn Phòng Chính Phủ",
      "Được giao nhiệm vụ chế tác pho tượng Bác Hồ đặt tại Văn phòng Chính phủ là trọng trách vẻ vang và đòi hỏi tiêu chuẩn khắt khe nhất về mỹ thuật lẫn kỹ thuật đúc. Dưới sự chỉ đạo khắt khe của Hội đồng nghệ thuật quốc gia, nghệ nhân Dương Bá Tiến cùng các cộng sự đã dồn toàn bộ tâm huyết, tạo tác nên pho tượng Bác với từng nếp áo, chòm râu chuẩn mực, toát lên thần thái ung dung tự tại của vị Cha già dân tộc.",
      "### 6. Đại Tượng Bác Hồ Nặng 30 Tấn Tại Sơn La & 1.000 Tượng Quà Tặng",
      "Đây là siêu công trình đi vào lịch sử ngành đúc đồng Việt Nam. Lộc Nam đã hoàn thành xuất sắc việc đúc Tượng Chủ tịch Hồ Chí Minh với đồng bào các dân tộc Tây Bắc có trọng lượng khổng lồ lên tới 30 tấn, đặt tại Quảng trường Tây Bắc (Sơn La). Đồng thời, xưởng đã chế tác thành công 1.000 sản phẩm tượng Bác Hồ thu nhỏ làm quà tặng ý nghĩa cho các đại biểu và nhân dân.",
      "Đại lễ đúc tượng và khánh thành đã vinh dự được đón tiếp các đồng chí lãnh đạo cấp cao của Đảng và Nhà nước về dự:",
      "- Đồng chí Tống Thị Phong (nguyên Ủy viên Bộ Chính trị, nguyên Phó Chủ tịch Thường trực Quốc hội)",
      "- Đồng chí Trần Quốc Vượng (nguyên Ủy viên Bộ Chính trị, nguyên Thường trực Ban Bí thư)",
      "- Đồng chí Võ Văn Thưởng (nguyên Ủy viên Bộ Chính trị)",
      "- Cùng các đồng chí Ủy viên Trung ương Đảng, Bí thư, Chủ tịch UBND các tỉnh Tây Bắc.",
      "Sự thành công vang dội của công trình khẳng định năng lực đúc đồng quy mô lớn hàng đầu Việt Nam của Lộc Nam.",
      "### 7. Đúc Chùa Đồng - Non Thiêng Núi Rừng Yên Tử",
      "Đỉnh thiêng Yên Tử (Quảng Ninh) quanh năm mây mù và gió lớn ở độ cao 1.068m là nơi tọa lạc của ngôi Chùa Đồng linh thiêng bậc nhất Việt Nam. Lộc Nam tự hào là đơn vị góp phần then chốt trong quá trình chế tác và gia công các chi tiết cấu kiện đồng đúc nguyên khối cho Chùa Đồng. Từng vì kèo, mái ngói, câu đối đều được tính toán kết cấu ngàm khóa chính xác tuyệt đối, trường tồn cùng phong ba ngàn năm nơi đất Phật Trúc Lâm.",
      "### 8. Đúc Tượng, Lư Đỉnh Và Toàn Bộ Đồ Thờ Đền Trần - Nam Định",
      "Ngay trên chính mảnh đất quê hương, Lộc Nam vinh dự phụng dựng không gian thờ tự tại Di tích Quốc gia đặc biệt Đền Trần (Nam Định). Hệ thống lư hương khổng lồ, đỉnh đồng, chuông đồng và các pho tượng đức thánh Trần Triều được đúc theo đúng chuẩn thức tâm linh cổ truyền, toát lên hào khí Đông A oanh liệt muôn đời.",
      "![Không gian thờ cúng linh thiêng với các vật phẩm đồng đúc thủ công tại Đền Trần Nam Định](/images/locnam_real/locnam_dinh_dong.jpg)",
      "## Năng Lực Sản Xuất Hàng Khối Lớn Theo Công Nghệ Khuôn Mẫu Độc Bản",
      "Bên cạnh các đại công trình kiến trúc, Đồ Đồng Lộc Nam là đối tác chiến lược trong các đơn hàng quà tặng cấp cao nhờ năng lực đúc hàng nghìn sản phẩm đồng nhất:",
      "- Quà Tặng Hội Nghị Thượng Đỉnh APEC 2017: Lộc Nam vinh dự chế tác các pho tượng Mẫu Âu Cơ và biểu trưng di sản văn hóa làm quà tặng ngoại giao trao tận tay các nguyên thủ quốc gia hàng đầu thế giới tham dự APEC Việt Nam 2017.",
      "- Gần 2.000 Pho Tượng Thần Tài Tại Núi Thần Tài (Đà Nẵng): Chế tác thần tốc gần 2.000 pho tượng Thần Tài bằng đồng sắc nét, an vị tại khu du lịch suối khoáng nóng Núi Thần Tài – biểu tượng cầu chúc tài lộc và hanh thông cho hàng triệu du khách thập phương.",
      "- 1.000 Quà Tặng Cao Cấp Cho Công Ty Tân Huê Viên: Cung ứng trọn gói 1.000 tác phẩm mỹ nghệ bằng đồng mạ vàng tinh xảo làm quà tặng tri ân khách hàng và đối tác trong các sự kiện đại tiệc trang trọng.",
      "- 1.000 Pho Tượng Bác Hồ Gửi Tặng Đồng Bào Tây Bắc: Chiến dịch xã hội đầy nhân văn mang hình ảnh Bác Hồ kính yêu về với từng bản làng vùng cao biên cương Tổ quốc.",
      "![Gần 2000 pho tượng Thần Tài đúc đồng an vị tại khu du lịch suối khoáng nóng Núi Thần Tài Đà Nẵng](/images/du_an/tuong-than-tai-da-nang.jpg)",
      "## Năng Lực Thi Công & Cam Kết Với Các Cơ Quan Doanh Nghiệp Lớn",
      "- Hồ sơ năng lực pháp lý minh bạch: Đầy đủ hóa đơn VAT, chứng thư giám định chất lượng kim loại, chứng chỉ tuổi vàng từ các viện kiểm định uy tín quốc gia.",
      "- Kinh nghiệm thi công siêu trường: Làm chủ hoàn toàn công nghệ đúc tượng đơn khối từ vài chục kilogam đến hàng chục tấn, lắp đặt an vị an toàn tuyệt đối ở mọi địa hình hiểm trở.",
      "- Bảo mật thông tin dự án: Tuyệt đối tôn trọng bản quyền mẫu mã và tính bảo mật của các sự kiện chính trị – đối ngoại.",
      "- Bảo hành công trình trọn đời: Cam kết đồng hành bảo trì, đánh bóng định kỳ cho các công trình văn hóa tâm linh trường tồn qua các thế hệ.",
      "## Liên Hệ Hợp Tác Dự Án & Thi Công Tượng Đài",
      "- CÔNG TY TNHH CƠ KHÍ ĐÚC LỘC NAM",
      "- Trưởng Ban Dự Án & Nghệ Nhân: Dương Bá Tiến",
      "- Hotline Dự án: 0336.222.222 – 0836.122.222",
      "- Xưởng sản xuất: Làng nghề đúc đồng Ý Yên, Tỉnh Nam Định",
      "- Website: https://www.quatanglocnam.com",
      "- Email: contact@quatanglocnam.com"
    ]
  },
  {
    slug: "so-do-va-cach-sap-xep-ban-tho-gia-tien-chuan-phong-thuy-ngu-hanh",
    title: "Sơ Đồ & Cách Sắp Xếp Bàn Thờ Gia Tiên Chuẩn Phong Thủy Ngũ Hành Rước Tài Lộc",
    summary: "Cẩm nang hướng dẫn sơ đồ bài trí bàn thờ gia tiên chuẩn phong thủy ngũ hành từ nghệ nhân Lộc Nam: Vị trí đặt đỉnh đồng, đôi hạc, chân nến, bát hương, mâm bồng chuẩn nguyên tắc 'Đông bình Tây quả', 'Tiền lư Hậu đỉnh' giúp tụ khí sinh tài, gia đạo bình an.",
    category: "CẨM NANG PHONG THỦY",
    date: "14/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/locnam_bo_do_tho.jpg",
    readTime: "11 phút đọc",
    keywords: [
      "cách sắp xếp bàn thờ gia tiên",
      "sơ đồ bài trí bàn thờ gia tiên",
      "vị trí đặt đỉnh đồng hạc nến",
      "bàn thờ gia tiên chuẩn phong thủy",
      "bộ ngũ sự đặt như thế nào",
      "nguyên tắc đông bình tây quả",
      "đồ đồng lộc nam",
      "đồ thờ cúng nam định",
      "bài trí bàn thờ chuẩn phong thủy"
    ],
    content: [
      "Bàn thờ gia tiên là chốn tôn nghiêm kết nối cội nguồn, nơi con cháu bày tỏ lòng hiếu kính và tri ân các bậc tiền nhân. Trong phong thủy thờ cúng của người Việt, việc sắp xếp các vật phẩm thờ tự đúng phương vị không chỉ mang lại nét trang nghiêm, thanh tịnh cho không gian tâm linh mà còn giúp kích hoạt long mạch, tụ khí sinh tài, đem lại bình an và phú quý dài lâu cho toàn gia đạo.",
      "Tuy nhiên, không ít gia chủ khi thỉnh bộ đồ thờ bằng đồng về vẫn băn khoăn: Đỉnh đồng nên đặt trước hay sau bát hương? Đôi hạc chầu quay hướng nào? Bình hoa và mâm quả sắp xếp ra sao cho đúng quy luật 'Đông bình Tây quả'?",
      "Bài viết dưới đây từ các nghệ nhân kỳ cựu của Xưởng Đúc Đồng Lộc Nam (Ý Yên, Nam Định) sẽ cung cấp sơ đồ bài trí chuẩn mực, phân tích quy luật ngũ hành và các nguyên tắc phong thủy giúp gia chủ an tâm sắp đặt trọn vẹn chốn thờ tự linh thiêng.",
      "## PHẦN 1: QUY TẮC NGŨ HÀNH TƯƠNG SINH TRÊN BÀN THỜ GIA TIÊN",
      "Một không gian thờ cúng chuẩn mực cần hội tụ đủ 5 yếu tố Ngũ Hành (Kim - Mộc - Thủy - Hỏa - Thổ) tương sinh, hỗ trợ lẫn nhau:",
      "- Hành Kim: Đại diện bởi bộ đồ thờ bằng đồng (đỉnh đồng, đôi hạc, chân nến, mâm bồng, ống hương bằng đồng). Kim mang tính bền vững, sáng ngời, tượng trưng cho sự trường tồn và phúc lộc dồi dào.",
      "- Hành Mộc: Đại diện bởi bàn thờ bằng gỗ tự nhiên (gỗ mít, gỗ gụ, gỗ hương) hoặc bài vị, đũa thờ gỗ.",
      "- Hành Thủy: Đại diện bởi chén nước, chén rượu thanh tịnh đặt trên kỷ ngai thờ và bình hoa tươi chứa nước.",
      "- Hành Hỏa: Đại diện bởi ánh lửa đèn dầu, nến thắp hoặc nén hương trầm đỏ ấm cúng khi hành lễ.",
      "- Hành Thổ: Đại diện bởi tro nếp thơm hoặc cát phong thủy trong lòng bát hương, kết hợp với các bình hoa sứ hoặc đồ đất nung.",
      "> Lưu ý của nghệ nhân: Khi ngũ hành cân bằng, dương khí và âm khí hòa hợp, bàn thờ sẽ trở thành tụ điểm năng lượng tốt nhất trong ngôi nhà, che chở mọi thành viên khỏi tà khí và vận xui.",
      "## PHẦN 2: SƠ ĐỒ BỐ TRÍ BÀN THỜ THEO 3 TẦNG CHIỀU SÂU 'TIỀN - TRUNG - HẬU'",
      "Để bàn thờ có chiều sâu uy nghiêm và thuận tiện cho việc thắp hương, dâng lễ, không gian bàn thờ được phân chia theo 3 lớp chính:",
      "### 1. Tầng Hậu (Lớp Trong Cùng Sát Vách Bàn Thờ)",
      "- Ngai thờ / Khám thờ / Bài vị gia tiên: Đặt tại vị trí cao nhất chính giữa, sát tường gỗ hoặc bức vách phòng thờ.",
      "- Đỉnh đồng (Lư hương lớn): Đặt chính giữa bàn thờ, ngay phía trước khám thờ hoặc bài vị. Nắp đỉnh đồng có con Nghê uy nghi quay đầu nhìn thẳng ra phía trước để trấn áp hung khí và canh giữ long mạch gia trạch.",
      "- Đôi Hạc đồng cưỡi kim quy: Đặt đối xứng hai bên đỉnh đồng, mỏ hạc ngậm cành hoa sen hướng chầu vào đỉnh thờ. Khoảng cách giữa thân đỉnh và hạc từ 5cm đến 10cm tùy kích thước bàn thờ.",
      "### 2. Tầng Trung (Lớp Ở Giữa)",
      "- Đôi chân nến bằng đồng: Đặt ở hai góc phía ngoài của đôi hạc, hơi chếch về mép ngoài bàn thờ. Chân nến bên trái tượng trưng cho hành Dương (Mặt Trời), chân nến bên phải tượng trưng cho hành Âm (Mặt Trăng), thể hiện nhật nguyệt chiếu rọi tâm can con cháu.",
      "- Bát hương (Pháp bảo cốt lõi): Đặt tại vị trí trung tâm, phía trước đỉnh đồng. Khoảng cách từ đỉnh đồng đến bát hương cần đủ rộng (khoảng 10cm - 15cm) để gia chủ dễ dàng cắm hương mà không bị vướng.",
      "- Cách bài trí 3 bát hương chuẩn: Bát hương thờ Thần Linh ngự ở giữa (kích thước to nhất và kê cao nhất). Bát hương thờ Gia Tiên đặt bên tay phải (theo hướng người đứng cúng nhìn vào). Bát hương thờ Bà Cô Tổ, Ông Mãnh đặt bên tay trái.",
      "### 3. Tầng Tiền (Lớp Phía Trước Mép Ngoài Cùng Bàn Thờ)",
      "- Mâm bồng (Đĩa đựng hoa quả, ngũ quả): Đặt phía trước bát hương, cách mép bàn thờ khoảng 5cm.",
      "- Kỷ ngai chén thờ (3 chén hoặc 5 chén): Đặt ở vị trí trước mâm bồng, ngay mép ngoài cùng bàn thờ, dùng để dâng nước thanh tịnh và rượu lễ.",
      "- Đôi đèn dầu thờ hoặc đèn thờ quả dứa bằng đồng: Đặt ở hai góc mép ngoài cùng bàn thờ để thắp sáng không gian.",
      "- Bình hoa & Ống hương: Bày đối xứng hai bên hồi bàn thờ theo nguyên tắc 'Đông bình Tây quả'.",
      "## PHẦN 3: 4 NGUYÊN TẮC PHONG THỦY 'BẤT DI BẤT DỊCH' KHI BÀY BÀN THỜ",
      "### 1. Nguyên Tắc 'Đông Bình Tây Quả'",
      "- Xuất xứ từ quy luật tự nhiên: Mặt trời mọc ở đằng Đông (hoa nở sinh sôi) và lặn ở đằng Tây (kết trái ngọt ngào).",
      "- Khi gia chủ đứng hướng mặt vào bàn thờ: Bình hoa đặt ở phía bên tay trái (phía Đông), mâm ngũ quả đặt ở phía bên tay phải (phía Tây) để đón lộc từ đất trời.",
      "### 2. Nguyên Tắc 'Tiền Lư Hậu Đỉnh'",
      "- Quy tắc truyền thống chuẩn mực nhất hiện nay: Đỉnh đồng đặt ở phía sau, Bát hương đặt ở phía trước. Ưu điểm của cách bố trí này là tạo thế tựa vững chãi của đỉnh đồng che chở phía sau, đồng thời gia chủ cắm hương hàng ngày dễ dàng, không lo bị bỏng hoặc vướng tay vào nắp nghê.",
      "### 3. Nguyên Tắc Cân Bằng 'Tả Thanh Long – Hữu Bạch Hổ'",
      "- Phía bên trái bàn thờ (Thanh Long): Bày các vật phẩm cao và mang tính dương như bình hoa đồng cỡ lớn hoặc chân nến cao.",
      "- Phía bên phải bàn thờ (Bạch Hổ): Bày các vật phẩm thấp và mang tính tĩnh như đĩa trầu cau hoặc mâm bồng vừa phải.",
      "### 4. Bát Hương Tuyệt Đối Bất Di Bất Dịch",
      "- Bát hương là điểm hội tụ khí thiêng của gia tiên. Khi đã làm lễ an vị thì tuyệt đối không được xê dịch vị trí tùy tiện.",
      "- Khi bao sái ban thờ ngày Tết hoặc ngày giỗ chạp, dùng một tay giữ chặt thân bát hương, tay kia dùng khăn mềm nhúng rượu gừng lau nhẹ nhàng xung quanh.",
      "## PHẦN 4: BẢNG TRA KÍCH THƯỚC BÀN THỜ & BỘ ĐỒ THỜ BẰNG ĐỒNG THEO THƯỚC LỖ BAN",
      "Chọn bộ đồ thờ tương xứng với kích thước ban thờ là điều kiện tiên quyết để đạt cung phong thủy tốt lành:",
      "- Bàn thờ dài 1m27 đến 1m55 (Sâu 61cm - 69cm): Thích hợp với bộ đỉnh đồng cao 45cm (Cung Tiến Bảo). Nên chọn bộ Tam Sự để không gian thông thoáng.",
      "- Bàn thờ dài 1m75 đến 1m97 (Sâu 81cm - 97cm): Kích thước bàn thờ chuẩn nhất của đa số gia đình Việt. Thích hợp bài trí trọn bộ Ngũ Sự đồng cao 50cm hoặc 60cm (Cung Đăng Khoa, Thêm Đinh, Tài Lộc).",
      "- Bàn thờ dài 1m97 đến 2m17 (Sâu 97cm - 107cm): Thích hợp bài trí bộ Ngũ Sự cao 65cm hoặc 70cm đúc đồng đỏ hoặc đồng cát tút uy nghi.",
      "- Nhà thờ họ, Từ đường (Bàn thờ dài trên 2m17): Bày bộ đỉnh 70cm trở lên kết hợp đôi hạc chầu đứng sàn cao 1m60 đến 1m80 và bộ hoành phi câu đối đồng chạm tay.",
      "## PHẦN 5: NHỮNG ĐIỀU ĐẠI KỴ CẦN TRÁNH KHI SẮP XẾP BÀN THỜ GIA TIÊN",
      "- Không đặt bàn thờ đối diện thẳng cửa nhà vệ sinh, nhà tắm hoặc ngay dưới xà ngang trần nhà.",
      "- Không đặt bàn thờ trong phòng ngủ hoặc nơi ẩm thấp, thiếu ánh sáng tự nhiên.",
      "- Không để hoa héo, lá khô hoặc trái cây giả bằng nhựa trên bàn thờ gia tiên lâu ngày.",
      "- Đồ đồng thờ cúng cần giữ sạch sẽ, định kỳ lau bằng khăn khô mềm để bề mặt luôn sáng đẹp tôn nghiêm.",
      "## PHẦN 6: ĐỒ ĐỒNG LỘC NAM – ĐỊA CHỈ TƯ VẤN & CUNG CẤP ĐỒ THỜ TẬN XƯỞNG Ý YÊN",
      "Xưởng Đúc Đồng Lộc Nam với đội ngũ nghệ nhân truyền thống làng nghề Ý Yên - Nam Định luôn sẵn sàng khảo sát, đo đạc và tư vấn trực tiếp sơ đồ bài trí bàn thờ gia tiên chuẩn thước Lỗ Ban theo mệnh gia chủ hoàn toàn miễn phí.",
      "- Địa chỉ xưởng: Cụm Công Nghiệp Làng Nghề Đúc Đồng Ý Yên, Tỉnh Nam Định.",
      "- Hotline tư vấn phong thủy 24/7: 0846 699 997 – 0836 122 222",
      "- Website chính thức: https://www.quatanglocnam.com",
      "- Chính sách: Giao hàng tận nhà, kiểm tra hàng đúng chất lượng đồng đỏ nguyên chất mới thanh toán, bảo hành trọn đời."
    ]
  },
  {
    slug: "bao-gia-duc-tuong-chan-dung-bang-dong-truyen-than-2026",
    title: "Báo Giá Đúc Tượng Chân Dung Bằng Đồng Truyền Thần 2026: Bảng Giá Xưởng & Quy Trình Đắp Mẫu Ý Yên",
    summary: "Bảng báo giá chi tiết dịch vụ đúc tượng chân dung ông bà, cha mẹ, danh nhân bằng đồng đỏ nguyên khối tận xưởng Ý Yên Nam Định năm 2026. Quy trình đắp mẫu đất sét 1:1, cam kết truyền thần giống trên 99%, duyệt mẫu trực tiếp trước khi rót đồng.",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "13/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/tuong_chan_dung/tuong_cd_01.jpg",
    readTime: "9 phút đọc",
    keywords: [
      "báo giá đúc tượng chân dung bằng đồng",
      "đúc tượng truyền thần giá bao nhiêu",
      "đúc tượng bố mẹ ông bà",
      "đúc tượng chân dung nam định",
      "giá đúc tượng đồng đỏ",
      "quy trình đắp mẫu tượng chân dung",
      "đồ đồng lộc nam",
      "đúc tượng đồng ý yên"
    ],
    content: [
      "Đúc tượng đồng chân dung truyền thần (đúc tượng ông bà, cha mẹ, tiền nhân hoặc danh nhân lịch sử) là nét đẹp văn hóa thể hiện tấm lòng hiếu đạo 'Uống nước nhớ nguồn' sâu sắc của con cháu. Khác với những bức ảnh thờ có thể phai mờ theo năm tháng, một pho tượng chân dung bằng đồng đỏ nguyên khối có tuổi thọ trường tồn hàng trăm năm, lưu giữ trọn vẹn nét mặt, nụ cười và thần thái phúc hậu của người thân cho muôn đời sau.",
      "Tuy nhiên, đúc tượng chân dung là phân khúc đỉnh cao và khó nhất trong nghệ thuật đúc đồng. Rất nhiều gia đình thắc mắc: Chi phí đúc tượng chân dung truyền thần hiện nay là bao nhiêu? Cần chuẩn bị những tư liệu gì? Làm sao để đảm bảo tượng đúc ra giống người thật?",
      "Xưởng Đúc Đồng Lộc Nam xin gửi tới quý gia chủ bảng báo giá chi tiết tận xưởng năm 2026 cùng quy trình đắp mẫu đất nghiêm ngặt cam kết độ giống trên 99%.",
      "## PHẦN 1: BẢNG BÁO GIÁ ĐÚC TƯỢNG CHÂN DUNG ĐỒNG ĐỎ NGUYÊN KHỐI 2026",
      "Tại Xưởng Đúc Đồng Lộc Nam, 100% tượng chân dung được đúc từ phôi Đồng Đỏ thanh khiết (sử dụng dây cáp điện đỏ tuyển chọn loại 1). Dưới đây là bảng giá niêm yết tại xưởng không qua trung gian:",
      "### 1. Bảng Giá Tượng Chân Dung Bán Thân (Đầu & Ngực Có Bệ Chữ)",
      "- Tượng bán thân cao 38cm - 40cm (nặng ~12kg - 14kg): Giá từ 14.500.000đ – 16.000.000đ / pho.",
      "- Tượng bán thân cao 45cm - 48cm (nặng ~15kg - 18kg, kích thước phổ biến nhất trên ban thờ): Giá từ 17.500.000đ – 20.000.000đ / pho.",
      "- Tượng bán thân cao 60cm (nặng ~25kg - 28kg, thích hợp từ đường, nhà thờ họ): Giá từ 24.000.000đ – 27.000.000đ / pho.",
      "- Tượng bán thân cao 70cm - 80cm: Giá từ 30.000.000đ – 38.000.000đ / pho.",
      "### 2. Tùy Chọn Hoàn Thiện Bề Mặt & Mạ Dát Vàng Cao Cấp",
      "- Làm màu đồng mộc hoặc hun màu cánh gián giả cổ, phủ nano 2K bảo vệ: Miễn phí theo gói tiêu chuẩn.",
      "- Dát Vàng Ròng 9999 / Vàng Ta chuẩn tuổi: Cộng thêm từ 5.000.000đ – 12.000.000đ / pho tùy kích thước (có chứng thư cam kết vàng thật).",
      "- Mạ vàng điện phân 24k sáng bóng: Cộng thêm từ 6.500.000đ – 14.000.000đ / pho.",
      "### 3. Tượng Toàn Thân & Tượng Tỷ Lệ 1:1 Người Thật",
      "- Tượng chân dung toàn thân ngồi ghế bành / ngai rồng (cao 81cm, 107cm, 127cm): Giá từ 45.000.000đ – 90.000.000đ tùy trọng lượng và chi tiết hoa văn.",
      "- Tượng đứng toàn thân kích thước thực tế: Khảo sát và lên báo giá dự toán thiết kế riêng.",
      "> Lưu ý: Báo giá đã bao gồm trọn gói: Chi phí điêu khắc gia đắp mẫu đất sét, chỉnh sửa mẫu đất đến khi ưng ý, phôi đồng đỏ nguyên khối, gia công nguội chạm khắc tên tuổi ngày mất lên bệ tượng, đóng thùng xốp gỗ và vận chuyển tận nhà trên toàn quốc.",
      "## PHẦN 2: 4 YẾU TỐ QUYẾT ĐỊNH GIÁ TRỊ VÀ ĐỘ GIỐNG CỦA TƯỢNG ĐỒNG CHÂN DUNG",
      "### 1. Trình Độ Của Điêu Khắc Gia Đắp Mẫu Đất (Yếu Tố Cốt Tử 70%)",
      "Đúc tượng chân dung không thể dùng máy móc hay công nghệ 3D quét rập khuôn mà phụ thuộc hoàn toàn vào 'đôi bàn tay vàng' và con mắt thẩm mỹ của điêu khắc gia. Một nghệ nhân giỏi không chỉ tạc lại các đường nét nhân học (sống mũi, gò má, đôi mắt) mà còn phải bắt được 'cái thần' – ánh nhìn ấm áp, khóe miệng tươi tắn của nhân vật.",
      "### 2. Chất Liệu Đúc: Đồng Đỏ Thanh Khiết Tuyển Chọn",
      "Đồ Đồng Lộc Nam cam kết nói KHÔNG với đồng phế liệu hay đồng pha tạp chất. Đồng đỏ cáp điện nguyên chất có độ dẻo và độ chảy lỏng tối ưu ở 1.200°C, giúp dòng kim loại chảy tới từng nếp nhăn nhỏ nhất và sợi tóc mai, mang lại bề mặt tượng mịn màng, không bị rỗ xỉ hay giòn vỡ.",
      "### 3. Quy Trình Khách Hàng Trực Tiếp Duyệt Mẫu Đất",
      "Khác với các xưởng đúc thương mại tự ý đúc rồi ép khách nhận hàng, tại Lộc Nam, sau khi đắp mẫu đất xong, xưởng sẽ mời gia đình đến xưởng duyệt trực tiếp hoặc quay video góc xoay 360 độ độ nét cao. Điêu khắc gia sẽ lắng nghe ý kiến của từng người thân để điều chỉnh mắt, sống mũi, khóe cười cho tới khi gia đình hoàn toàn gật đầu mới chuyển sang khâu đổ khuôn đúc đồng.",
      "### 4. Kỹ Thuật Chạm Khắc Nguội Sau Khi Đúc",
      "Khi dỡ khuôn đất, pho tượng thô sẽ được các nghệ nhân kim hoàn dùng đục thép tỉ mỉ chạm gọt từng sợi lông mày, nếp áo và con ngươi mắt, tạo nên chiều sâu sống động như thật.",
      "## PHẦN 3: QUY TRÌNH 6 BƯỚC ĐÚC TƯỢNG CHÂN DUNG TẠI XƯỞNG LỘC NAM",
      "- Bước 1 (Tiếp nhận tư liệu): Khách hàng gửi ảnh chụp nhân vật (ảnh thẻ, ảnh chụp kỷ niệm, ảnh chụp nghiêng góc 45 độ và góc 90 độ nếu có) kèm mô tả đặc điểm nhận dạng đặc trưng.",
      "- Bước 2 (Đắp mẫu đất sét 1:1): Điêu khắc gia tốt nghiệp Đại học Mỹ Thuật tạo hình mẫu đất sét trong 5-7 ngày.",
      "- Bước 3 (Chỉnh sửa và duyệt mẫu): Gia đình thẩm định mẫu đất, góp ý chỉnh sửa chi tiết. Lộc Nam chỉ tiến hành đúc khi khách hàng duyệt mẫu 100%.",
      "- Bước 4 (Tạo khuôn thạch cao & làm khuôn đồng âm dương): Đổ khuôn thạch cao bảo lưu chi tiết mẫu đất, sau đó trát đất sét chịu nhiệt và nung chín khuôn trong lò.",
      "- Bước 5 (Nấu và rót đồng đỏ): Đun nóng chảy đồng đỏ cáp điện ở nhiệt độ 1.200°C và rót vào khuôn liền mạch.",
      "- Bước 6 (Làm nguội, chạm tỉa & phủ nano 2K): Nghệ nhân sửa nguội, chạm khắc thông tin lên bệ tượng, làm màu theo yêu cầu và phủ bóng bảo vệ.",
      "## PHẦN 4: KHÁCH HÀNG CẦN CHUẨN BỊ GÌ TRƯỚC KHI ĐẶT ĐÚC TƯỢNG?",
      "- Tư liệu ảnh: Cung cấp ảnh rõ nét nhất có thể. Nếu chỉ có ảnh cũ chụp đen trắng thời bao cấp mờ, nghệ nhân giàu kinh nghiệm của Lộc Nam vẫn có thể dựng lại dựa trên tư vấn trực tiếp từ con cháu.",
      "- Thời gian đặt hàng: Toàn bộ quá trình từ đắp mẫu đến bàn giao tượng đồng hoàn thiện thường mất từ 20 đến 30 ngày. Gia đình chuẩn bị làm lễ mừng thọ, khánh thành từ đường hoặc lễ giỗ nên đặt trước tối thiểu 1 tháng.",
      "## PHẦN 5: CHÍNH SÁCH CAM KẾT VÀNG TỪ ĐỒ ĐỒNG LỘC NAM",
      "- Cam kết thần thái: Tượng đạt độ giống và thần thái trên 99% so với mẫu đất đã được gia đình phê duyệt.",
      "- Cam kết chất liệu: Đền tiền gấp 10 lần nếu phát hiện đồng pha chì hoặc đồng tạp chất kém chất lượng.",
      "- Bảo hành: Bảo hành chất lượng đồng vĩnh cửu trọn đời.",
      "- Giao hàng: Miễn phí vận chuyển toàn quốc, kiểm tra tượng tận tay mới thanh toán.",
      "## LIÊN HỆ ĐẶT ĐÚC TƯỢNG TRUYỀN THẦN",
      "- Xưởng chính: Làng Nghề Đúc Đồng Truyền Thống Ý Yên, Tỉnh Nam Định.",
      "- Hotline / Zalo tư vấn nghệ nhân: 0846 699 997 – 0836 122 222",
      "- Website: https://www.quatanglocnam.com"
    ]
  },
  {
    slug: "5-cach-danh-bong-lam-sang-do-dong-bi-xin-mau-tai-nha",
    title: "5 Cách Đánh Bóng Làm Sáng Đồ Đồng Bị Xỉn Màu Tại Nhà Đơn Giản, Hiệu Quả 100% Không Làm Hại Bề Mặt",
    summary: "Hướng dẫn 5 mẹo dân gian và phương pháp chuyên nghiệp giúp làm sạch lư hương, đỉnh đồng, chân nến bị hoen gỉ, ố đen bằng nguyên liệu tự nhiên quen thuộc: chanh tươi, giấm ăn, baking soda, kem đánh răng. Đảm bảo đồ thờ sáng bóng như mới đón tài lộc.",
    category: "BẠN CÓ BIẾT",
    date: "13/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/bo-do-tho-ma-vang.jpg",
    readTime: "8 phút đọc",
    keywords: [
      "cách đánh bóng đồ đồng",
      "làm sáng đồ đồng bị xỉn màu",
      "cách tẩy đồ đồng tại nhà",
      "đánh bóng lư hương đồng",
      "mẹo làm mới đồ thờ bằng đồng",
      "tẩy rỉ đồng xanh",
      "đồ đồng lộc nam",
      "vệ sinh bộ đỉnh đồng gia tiên"
    ],
    content: [
      "Sau nhiều năm ngự trên bàn thờ gia tiên, chịu ảnh hưởng từ khói hương, tàn nhang, độ ẩm không khí và bụi bẩn, các vật phẩm đồ đồng như đỉnh đồng, lư hương, đôi hạc, chân nến thường xuất hiện tình trạng xỉn màu, ố đen hoặc xuất hiện các vệt ố xanh (gỉ đồng). Điều này khiến không gian thờ cúng giảm bớt vẻ trang nghiêm, sáng đẹp vốn có.",
      "Nhiều gia chủ muốn tự tay bao sái, làm mới bộ đồ thờ tại nhà dịp cuối năm, ngày giỗ chạp nhưng lo sợ dùng sai hóa chất sẽ làm ăn mòn hoặc làm hỏng lớp hoa văn chạm trổ thủ công quý giá.",
      "Đừng lo lắng! Nghệ nhân Đồ Đồng Lộc Nam xin chia sẻ 5 công thức đánh bóng đồ đồng bị xỉn màu tại nhà cực kỳ đơn giản, an toàn bằng các nguyên liệu tự nhiên sẵn có trong gian bếp, hiệu quả sáng bóng đạt 100% ngay từ lần đầu tiên.",
      "## NGUYÊN NHÂN KHIẾN ĐỒ ĐỒNG BỊ XỈN MÀU & NGUYÊN TẮC CẦN BIẾT",
      "Về mặt khoa học, đồng là kim loại có phản ứng oxy hóa chậm với oxy trong không khí, khí CO2 và độ ẩm, tạo thành lớp oxit đồng (CuO màu đen hoặc Cu2(OH)2CO3 màu xanh xám). Đây là hiện tượng vật lý hoàn toàn tự nhiên của đồng nguyên chất.",
      "> CẢNH BÁO QUAN TRỌNG: Các phương pháp tẩy sáng dưới đây CHỈ áp dụng cho đồ đồng vàng, đồng đỏ nguyên mộc cần lấy lại màu vàng sáng bóng. TUYỆT ĐỐI KHÔNG áp dụng cho đồ đồng khảm tam khí, khảm ngũ sắc hoặc đồ đồng hun rêu giả cổ cao cấp, vì các chất có tính axit sẽ làm bay màu lớp hun nghệ thuật.",
      "## 5 CÁCH ĐÁNH BÓNG ĐỒ ĐỒNG TẠI NHÀ HIỆU QUẢ NHẤT",
      "### Cách 1: Sử Dụng Chanh Tươi & Muối Hạt (Phương Pháp Dân Gian An Toàn Nhất)",
      "Axit citric tự nhiên trong quả chanh kết hợp với tính mài mòn nhẹ của muối biển là 'khắc tinh' của các mảng bám oxy hóa trên bề mặt đồng.",
      "- Nguyên liệu: 2 - 3 quả chanh tươi mọng nước, 1 bát muối hạt giã mịn, khăn mềm hoặc miếng mút rửa bát.",
      "- Các bước thực hiện:",
      "- Bước 1: Cắt đôi quả chanh, chấm trực tiếp mặt cắt vào bát muối hạt.",
      "- Bước 2: Chà nhẹ nhàng lên bề mặt đỉnh đồng hoặc chân nến theo hình xoắn ốc. Nước cốt chanh và muối sẽ phản ứng làm tan lớp oxit đồng đen xỉn chỉ sau 1-2 phút.",
      "- Bước 3: Dùng bàn chải đánh răng lông mềm chà nhẹ vào các khe kẽ hoa văn rồng chầu, mây lượn để lấy đi vết bẩn cứng đầu.",
      "- Bước 4: Rửa sạch lại bằng nước ấm và dùng khăn cotton khô lau thật ráo nước.",
      "### Cách 2: Dùng Hỗn Hợp Giấm Ăn & Bột Mì (Công Thức 'Kem Tẩy' Cổ Truyền)",
      "Giấm ăn (axit axetic) hòa quyện cùng bột mì tạo thành một lớp bùn dính giữ axit trên bề mặt kim loại lâu hơn mà không bị chảy nhỏ giọt.",
      "- Nguyên liệu: 1 bát bột mì đa dụng, 2 thìa canh giấm trắng, 1 thìa muối tinh.",
      "- Các bước thực hiện:",
      "- Bước 1: Trộn đều bột mì, giấm và muối để tạo thành hỗn hợp sền sệt dạng bột nhão.",
      "- Bước 2: Dùng cọ quét đều lớp bột này lên toàn bộ thân đỉnh đồng, chân hạc và bát hương.",
      "- Bước 3: Để yên trong khoảng 15 - 20 phút cho hỗn hợp khô lại và hút sạch các tạp chất oxy hóa.",
      "- Bước 4: Dùng khăn ấm lau sạch lớp bột mì khô. Bạn sẽ thấy phôi đồng bên dưới bừng sáng như vừa xuất xưởng!",
      "### Cách 3: Sử Dụng Baking Soda (Muối Nở) & Nước Cốt Chanh",
      "Phản ứng sủi bọt khí CO2 giữa baking soda kiềm nhẹ và chanh axit tạo ra hàng triệu bọt vi mô len lỏi vào các chi tiết hoa văn chạm âm bản sâu nhất.",
      "- Nguyên liệu: 2 thìa bột baking soda, nước cốt 1 quả chanh.",
      "- Các bước thực hiện:",
      "- Bước 1: Cho baking soda vào chén nhỏ, từ từ đổ nước cốt chanh vào cho đến khi hỗn hợp sủi bọt tạo thành chất kem sánh mịn.",
      "- Bước 2: Dùng khăn mềm hoặc bàn chải thấm kem này thoa đều lên bề mặt đồ đồng.",
      "- Bước 3: Chà nhẹ tay trong 3 - 5 phút, tập trung vào những vị trí bị gỉ xanh hoặc hoen ố đen.",
      "- Bước 4: Rửa lại bằng nước sạch và dùng máy sấy tóc sấy khô hoàn toàn các ngóc ngách.",
      "### Cách 4: Sử Dụng Kem Đánh Răng Thông Dụng",
      "Trong kem đánh răng có chứa các hạt siêu mịn silica và chất làm sạch, rất thích hợp để đánh bóng các vật phẩm đồ đồng nhỏ như đài sen, chén nước, thìa trầm hương mà không lo bị xước.",
      "- Các bước thực hiện:",
      "- Bước 1: Bôi một lượng kem đánh răng vừa đủ lên bề mặt đồ đồng.",
      "- Bước 2: Dùng khăn ẩm hoặc bàn chải mềm xoa đều và miết nhẹ theo chiều hoa văn.",
      "- Bước 3: Sau khoảng 5 phút, rửa sạch bằng nước ấm và lau khô ráo.",
      "### Cách 5: Sử Dụng Kem Đánh Bóng Chuyên Dụng Autosol Hoặc Cana",
      "Đối với những bộ đồ đồng cổ để lâu năm bị rỉ đồng xanh bám kết dày bản, các nguyên liệu tự nhiên có thể mất nhiều thời gian. Khi đó, kem đánh bóng kim loại Autosol là giải pháp chuyên nghiệp tối ưu.",
      "- Cách làm: Lấy một lượng nhỏ kem Autosol chấm lên bề mặt đồng, dùng khăn nỉ hoặc vải thô chà miết dứt khoát. Bụi bẩn và rỉ đồng sẽ bám đen vào khăn, trả lại bề mặt đồng ánh kim sáng loáng như gương soi.",
      "## BÍ QUYẾT GIỮ ĐỒ ĐỒNG LUÔN SÁNG BÓNG TRÊN 10 NĂM KHÔNG BỊ Ố LẠI",
      "Sau khi làm sạch đồ đồng xong, khâu bảo quản là yếu tố quyết định đồ đồng có giữ được độ bóng lâu dài hay không:",
      "- Lau khô tuyệt đối: Sau khi rửa nước, phải lau khô kiệt nước và dùng máy sấy tóc hong khô mọi ngách nhỏ trước khi an vị lên bàn thờ. Nước đọng chính là thủ phạm gây rỉ xanh nhanh nhất.",
      "- Phủ lớp sáp bảo vệ: Có thể dùng một chút sáp ong mỏng hoặc dầu khoáng xoa đều lên bề mặt đồ đồng để tạo màng ngăn không khí tiếp xúc với kim loại.",
      "- Tránh chạm tay trần: Mồ hôi tay chứa muối và axit là tác nhân hàng đầu gây loang ố bề mặt đồng. Khi bưng bê, gia chủ nên dùng găng tay vải mỏng hoặc khăn mềm.",
      "## KHI NÀO NÊN GỬI BỘ ĐỒ THỜ VỀ XƯỞNG ĐÚC ĐỒNG LỘC NAM?",
      "Nếu bộ đồ thờ của gia đình bạn là dòng đồ đồng hun rêu, đồng khảm tam khí - ngũ sắc cổ truyền, hoặc bề mặt đã bị xước sâu theo năm tháng, việc tự tẩy tại nhà có thể làm mất đi giá trị thẩm mỹ. Hãy liên hệ với Xưởng Đúc Đồng Lộc Nam để được phục hồi, hun màu cổ kính và phủ lớp sơn bóng Nano 2K bảo hành trường tồn hàng chục năm.",
      "- Hotline tư vấn bảo quản đồ đồng: 0846 699 997 – 0836 122 222",
      "- Xưởng sản xuất: Làng Nghề Đúc Đồng Ý Yên, Tỉnh Nam Định.",
      "- Website: https://www.quatanglocnam.com"
    ]
  },
  {
    slug: "cam-nang-chon-mua-bo-do-tho-bang-dong-y-yen-nam-dinh",
    title: "Cẩm Nang Chọn Mua Bộ Đồ Thờ Bằng Đồng Ý Yên Nam Định: Phân Biệt Chất Liệu, Thước Lỗ Ban & Bảng Giá Xưởng 2026",
    summary: "Hướng dẫn toàn diện từ nghệ nhân xưởng đúc Lộc Nam: Cấu tạo bộ tam sự ngũ sự, phân biệt 4 loại đồng (đồng đỏ, đồng vàng, cát tút, mạ vàng 24k), bảng tra thước Lỗ Ban 38.8cm và báo giá tận xưởng không qua trung gian.",
    category: "CẨM NANG PHONG THỦY",
    date: "12/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/locnam_dinh_dong.jpg",
    readTime: "12 phút đọc",
    keywords: [
      "bộ đồ thờ bằng đồng",
      "đồ thờ cúng nam định",
      "đồ đồng lộc nam",
      "đỉnh đồng ý yên",
      "bộ ngũ sự bằng đồng",
      "báo giá đồ thờ bằng đồng",
      "thước lỗ ban bàn thờ",
      "đồ đồng đẹp nam định",
      "phân biệt đồng đỏ đồng thau",
      "cách bày bàn thờ gia tiên"
    ],
    content: [
      "Trong văn hóa tâm linh của người Việt, không gian thờ cúng gia tiên là nơi tôn nghiêm nhất trong mỗi gia đình, thể hiện lòng hiếu kính 'Uống nước nhớ nguồn' đối với tổ tiên, cội nguồn. Trong đó, bộ đồ thờ bằng đồng luôn là lựa chọn hàng đầu của các gia đình danh gia, quyền quý bởi vẻ đẹp uy nghiêm, độ bền trường tồn hàng trăm năm và ý nghĩa phong thủy hội tụ linh khí ngũ hành.",
      "Tuy nhiên, trước sự xuất hiện tràn lan của các dòng đồng pha chì, đồng Đài Loan dập máy mạ xi mỏng chỉ sau vài năm là xỉn ố, việc tìm mua được một bộ đồ thờ bằng đồng chuẩn làng nghề Ý Yên Nam Định nguyên chất, đúc thủ công tinh xảo là nỗi băn khoăn của rất nhiều gia chủ.",
      "Bài viết cẩm nang dưới đây của Xưởng Đúc Đồng Lộc Nam sẽ cung cấp cho bạn cái nhìn toàn diện từ cấu tạo bộ tam sự - ngũ sự, cách phân biệt các loại đồng, bảng tra kích thước theo thước Lỗ Ban và bảng báo giá chi tiết tận xưởng năm 2026.",
      "## PHẦN 1: CẤU TẠO BỘ ĐỒ THỜ BẰNG ĐỒNG GỒM NHỮNG GÌ? PHÂN BIỆT BỘ TAM SỰ VÀ BỘ NGŨ SỰ",
      "Tùy thuộc vào diện tích bàn thờ gia tiên và điều kiện của từng gia đình, bộ đồ thờ bằng đồng thường được chia làm 2 quy cách chính: Bộ Tam Sự (3 món) và Bộ Ngũ Sự (5 món).",
      "### 1. Đỉnh Đồng (Lư Hương) – Trái Tim Của Bàn Thờ Gia Tiên",
      "Đỉnh đồng là pháp bảo ngự tại vị trí chính giữa bàn thờ, dùng để đốt trầm hương trong các ngày mùng Một, ngày Rằm và lễ Tết.",
      "- Ý nghĩa tâm linh: Khói trầm thơm thanh khiết tỏa ra từ miệng nghê trên nắp đỉnh có tác dụng thanh tẩy tà khí, hóa giải hung khí, kích hoạt vượng khí và kết nối lòng thành của con cháu với tổ tiên nơi cõi thiêng.",
      "- Nắp đỉnh: Đúc nổi hình tượng Con Nghê vờn cầu – linh vật thuần Việt có linh lực trấn trạch, xua đuổi tà ma và bảo hộ gia trạch bình an.",
      "- Thân đỉnh: Bầu tròn hoặc vuông quả bóng, chạm khắc nổi bộ chữ Hán - Nôm mạ vàng 'Phúc - Lộc - Thọ - Khang - Ninh' kết hợp họa tiết Song Long Chầu Nguyệt tinh xảo.",
      "- Tai mây (Quai đỉnh): Đúc liền khối với thân đỉnh, uốn lượn hình mây cách điệu vững chãi.",
      "- Chân đỉnh: 3 chân đúc liền thân theo thế 'kiềng ba chân', chạm khắc đầu hổ phù uy nghiêm chống đỡ bầu đỉnh.",
      "- Đế đỉnh: Dáng tròn hoặc bát giác, vừa khít với 3 chân đỉnh, mặt trên chạm hoa văn rồng cuộn hoặc hoa sen thanh tịnh.",
      "### 2. Đôi Hạc Đồng Cưỡi Kim Quy – Biểu Tượng Trường Thọ & Tương Trợ Âm Dương",
      "Đặt đối xứng hai bên đỉnh đồng là đôi hạc đứng trên lưng rùa, đầu ngẩng cao, miệng ngậm cành hoa sen.",
      "- Hạc: Loài chim tiên cao quý, đại diện cho phẩm hạnh thanh cao, sự thuần khiết và khí tiết của người quân tử.",
      "- Rùa (Kim Quy): Loài bò sát trường thọ, đại diện cho đất mẹ vững chãi và sự bền bỉ chở che.",
      "- Triết lý nhân sinh: Hạc đứng trên lưng rùa tượng trưng cho tình nghĩa tương trợ keo sơn giữa trời và đất, âm và dương, nhắc nhở con cháu luôn sống hòa thuận, hiếu thảo và kiên định trước sóng gió cuộc đời.",
      "### 3. Đôi Chân Nến (Đèn Thờ) – Ánh Sáng Trí Tuệ & Nhật Nguyệt Giao Hòa",
      "Được đặt ở phía ngoài cùng hai bên bàn thờ, phía trước hoặc ngang hàng với đôi hạc:",
      "- Chân nến bên trái tượng trưng cho Mặt Trời (Dương khí).",
      "- Chân nến bên phải tượng trưng cho Mặt Trăng (Âm khí).",
      "- Sự hiện diện của đôi chân nến mang ý nghĩa nhật nguyệt giao hòa, sinh sôi nảy nở, soi đường chỉ lối cho con cháu hướng về đạo đức, công danh và sự nghiệp hanh thông.",
      "## PHẦN 2: KHOA HỌC LUYỆN KIM – CÁCH PHÂN BIỆT 4 CHẤT LIỆU ĐỒNG PHỔ BIẾN TRÊN THỊ TRƯỜNG",
      "Chất liệu đúc quyết định tới 80% giá trị và tuổi thọ của một bộ đồ thờ. Dưới đây là đặc tính 4 dòng đồng đang có trên thị trường hiện nay:",
      "### 1. Đồng Vàng Thau (Đồng Thau)",
      "- Thành phần: Đồng thanh khiết 65% - 70% kết hợp hợp kim kẽm để tăng độ chảy lỏng.",
      "- Màu sắc: Màu vàng sáng bóng tự nhiên hoặc hun rêu cổ trang nghiêm.",
      "- Trọng lượng: Bộ 60cm nặng khoảng 22kg - 25kg.",
      "- Độ bền: 20 - 30 năm, thích hợp cho phân khúc gia đình cần sự trang trọng với chi phí hợp lý.",
      "### 2. Đồng Đỏ Nguyên Chất (Đồng Mắt Cua)",
      "- Thành phần: Đồng đỏ thanh khiết 90% - 95% (sử dụng dây cáp điện đỏ tuyển chọn loại 1).",
      "- Màu sắc: Màu đỏ mắt cua trầm ấm, bóng mịn, càng dùng theo năm tháng càng lên nước cổ kính.",
      "- Trọng lượng: Bộ 60cm nặng từ 28kg - 32kg, cầm rất đầm tay và chắc chắn.",
      "- Độ bền: Trường tồn trên 70 năm, không lo nứt vỡ hay bay màu.",
      "### 3. Đồng Cát-Tút (Vỏ Đạn Pháo Quân Sự)",
      "- Thành phần: Đúc từ vỏ đạn pháo quân sự nguyên chất, tính dẻo và độ đanh cơ học cực cao.",
      "- Màu sắc: Ánh vàng xanh quân sự đặc trưng, âm thanh gõ vang ngân như tiếng chuông khánh.",
      "- Độ bền: Vĩnh cửu trên 80 năm, thuộc phân khúc thượng lưu.",
      "### 4. Đồng Khảm Tam Khí / Ngũ Sắc & Mạ Vàng 24K",
      "- Cốt đồng đỏ thanh khiết chạm khắc âm bản, sau đó nghệ nhân dùng búa gõ nạm từng lá Bạc 9999 và Vàng 24k nguyên chất vào từng đường hoa văn.",
      "- Đỉnh cao mỹ nghệ truyền thống, độ tinh xảo bậc nhất, giá trị truyền đời hàng trăm năm cho con cháu.",
      "> Lời khuyên của nghệ nhân Lộc Nam: Đối với bàn thờ gia tiên lâu dài, gia chủ nên ưu tiên lựa chọn chất liệu từ Đồng Đỏ nguyên khối hoặc Đồng Cát-Tút trở lên. Đồng đỏ có tính hàn, trầm mặc, rất hợp với chốn thờ tự linh thiêng.",
      "## PHẦN 3: BẢNG TRA KÍCH THƯỚC BỘ ĐỒ THỜ THEO THƯỚC LỖ BAN CHUẨN KÍCH THƯỚC BÀN THỜ",
      "Một sai lầm rất phổ biến là gia chủ chọn bộ đỉnh quá to khiến bàn thờ chật chội, hoặc chọn bộ đỉnh quá nhỏ khiến không gian thờ bị lọt thỏm. Dưới đây là bảng quy chuẩn vàng từ xưởng Lộc Nam:",
      "- Bàn thờ dài 1m27 đến 1m55 (Sâu 61cm - 69cm): Phù hợp với bộ đỉnh đồng cao 45cm (Cung Tiến Bảo, Thêm Đinh). Khuyên dùng bộ Tam sự 45cm.",
      "- Bàn thờ dài 1m75 đến 1m97 (Sâu 81cm - 97cm): Phù hợp với bộ đỉnh đồng cao 50cm hoặc 60cm (Cung Đăng Khoa, Tài Lộc). Đây là kích thước chuẩn mực phổ biến nhất cho gia đình Việt.",
      "- Bàn thờ dài 1m97 đến 2m17 (Sâu 97cm - 107cm): Phù hợp với bộ đỉnh đồng cao 65cm hoặc 70cm (Cung Đại Cát, Quý Tử).",
      "- Bàn thờ Tổ, Từ đường, Nhà thờ họ (Dài trên 2m17): Phù hợp với bộ đỉnh đồng cao 70cm trở lên kết hợp đôi hạc đứng sàn 1m60 hoặc 1m80 uy nghi.",
      "## PHẦN 4: HƯỚNG DẪN BÀY TRÍ BÀN THỜ GIA TIÊN ĐÚNG NGUYÊN TẮC 'ĐÔNG BÌNH TÂY QUẢ'",
      "Việc sắp đặt bộ đồ thờ đúng phương vị phong thủy giúp tụ khí sinh tài, con cháu trong nhà thuận hòa, học hành đỗ đạt:",
      "- 1. Đỉnh đồng: Đặt ở vị trí chính giữa bàn thờ, lùi về phía sau cùng (sát vách tường hoặc khám thờ). Nắp nghê quay mặt nhìn thẳng ra phía trước cửa phòng thờ.",
      "- 2. Đôi Hạc: Đặt chầu hai bên đỉnh đồng, mỏ hạc hướng vào thân đỉnh. Khoảng cách từ thân đỉnh tới chân hạc từ 5cm - 10cm.",
      "- 3. Đôi Chân nến: Đặt đối xứng hai bên ngoài đôi hạc, hơi chếch về phía trước của bàn thờ để thuận tiện thắp nến ngày rằm và tạo ánh sáng ấm áp.",
      "- 4. Bát hương: Ngự tại chính diện phía trước Đỉnh đồng. Nếu gia đình thờ 3 bát hương (Thần linh ở giữa, Gia tiên bên phải, Bà cô Tổ bên trái), bát hương Thần linh phải to và kê cao hơn hai bát hương còn lại.",
      "- 5. Mâm bồng & Ngai chén: Mâm ngũ quả đặt phía trước bát hương. Ngai 3 chén hoặc 5 chén nước đặt ở mép ngoài cùng bàn thờ.",
      "## PHẦN 5: QUY TRÌNH 7 BƯỚC ĐÚC ĐỒNG THỦ CÔNG MỸ NGHỆ TẠI XƯỞNG LỘC NAM",
      "- Bước 1: Tạo mẫu đất sét định hình tỷ lệ cân đối giữa bầu đỉnh, nắp nghê và chân lân.",
      "- Bước 2: Dùng đất phù sa sông Đáy trộn trấu và giấy dó làm khuôn đúc âm dương bản, sau đó sấy nung khuôn ở 700°C liên tục 3 ngày đêm.",
      "- Bước 3: Nấu đồng đỏ nguyên chất cùng kim khí quý trong lò nung đạt nhiệt độ trên 1.200°C.",
      "- Bước 4: Rót đồng sôi đỏ rực vào khuôn đều tay, đảm bảo dòng đồng chảy liền mạch không bị rỗ bọt khí.",
      "- Bước 5: Dỡ khuôn đất sau khi đồng nguội hoàn toàn, tiến hành làm sạch cốt đồng thô nguyên khối.",
      "- Bước 6: Nghệ nhân dùng đục thép chạm khắc tay từng đường vảy rồng, chữ Hán mạ vàng, tỉa tót đuôi hạc sắc sảo từng milimet.",
      "- Bước 7: Làm màu mắt cua, hun rêu giả cổ hoặc mạ vàng 24K, cuối cùng phủ lớp sơn bóng nano 2K bảo vệ chống oxy hóa tuyệt đối.",
      "## PHẦN 6: BẢNG BÁO GIÁ BỘ ĐỒ THỜ BẰNG ĐỒNG LỘC NAM MỚI NHẤT 2026 (GIÁ GỐC TẬN XƯỞNG)",
      "- Bộ Ngũ Sự Đồng Vàng Thau 50cm - 60cm: Từ 8.500.000đ – 12.500.000đ (Bảo hành 10 năm).",
      "- Bộ Ngũ Sự Đồng Vàng Hun Rêu Cổ 60cm: Từ 11.000.000đ – 14.500.000đ (Bảo hành 15 năm).",
      "- Bộ Ngũ Sự Đồng Đỏ Nguyên Khối 60cm (nặng ~30kg): Từ 18.500.000đ – 24.000.000đ (Bảo hành 20 năm).",
      "- Bộ Ngũ Sự Đồng Cát-Tút Vỏ Đạn 60cm - 65cm: Từ 26.000.000đ – 35.000.000đ (Bảo hành trọn đời).",
      "- Bộ Ngũ Sự Khảm Tam Khí Bạc 9999 Cao Cấp: Từ 28.000.000đ – 38.000.000đ (Bảo hành trọn đời).",
      "- Bộ Ngũ Sự Mạ Vàng Ròng 24K / Dát Vàng 9999: Từ 45.000.000đ – 75.000.000đ (Bảo hành trọn đời có chứng thư giám định vàng).",
      "> Lưu ý: Giá trên đã bao gồm chi phí đóng kiện gỗ và cước vận chuyển tận nhà trên toàn quốc. Khách hàng kiểm tra đúng mẫu mã, cân nặng mới thanh toán.",
      "## PHẦN 7: CÂU HỎI THƯỜNG GẶP KHI MUA ĐỒ THỜ BẰNG ĐỒNG (FAQ)",
      "### Đồ thờ bằng đồng của Lộc Nam có bị xỉn đen hay hoen gỉ không?",
      "Sản phẩm của Đồ Đồng Lộc Nam sau khi hoàn thiện đều được xử lý bề mặt kỹ lưỡng và phủ lớp bóng 2K nano chuyên dụng ngăn chặn hoàn toàn không khí tiếp xúc với bề mặt kim loại. Sản phẩm giữ độ sáng bóng từ 15 đến trên 30 năm, chỉ cần lau bằng khăn khô mềm định kỳ.",
      "### Khách hàng ở xa (Hà Nội, Đà Nẵng, TP.HCM) đặt mua thì nhận hàng thế nào?",
      "Xưởng Lộc Nam có mạng lưới giao hàng chuyên nghiệp bằng xe tải hoặc bưu điện hỏa tốc tận nhà. Mọi đơn hàng đều được bọc xốp bóng khí và đóng thùng gỗ kín. Khi hàng tới nơi, quý khách được quyền mở kiện hàng kiểm tra kỹ lưỡng hoa văn, cân nặng trước khi thanh toán tiền.",
      "### Xưởng có nhận đúc đồ thờ, tượng đồng theo yêu cầu riêng không?",
      "Có. Chúng tôi chuyên nhận đúc đỉnh đồng cỡ đại cho nhà thờ họ, đúc tượng chân dung truyền thần cụ ông/cụ bà giống ảnh 99%, đúc chuông đồng đại hồng chung và dát vàng 9999 theo yêu cầu riêng.",
      "## PHẦN 8: LIÊN HỆ ĐẶT HÀNG TẬN XƯỞNG ĐÚC ĐỒNG LỘC NAM",
      "- Trụ sở xưởng đúc chính: Cụm Làng Nghề Đúc Đồng Truyền Thống, Huyện Ý Yên, Tỉnh Nam Định.",
      "- Website chính thức: https://www.quatanglocnam.com",
      "- Hotline / Zalo tư vấn nghệ nhân 24/7: 0846 699 997 – 0836 122 222",
      "- Email tiếp nhận bản vẽ: dodonglocnam1102@gmail.com",
      "- Thời gian mở cửa đón tiếp khách: 07:30 – 21:30 tất cả các ngày trong tuần."
    ]
  },
  {
    slug: "bi-quyet-chon-do-tho-cung-bang-dong-nam-dinh",
    title: "Bí Quyết Chọn Đồ Thờ Cúng Bằng Đồng Nam Định Chuẩn Phong Thủy Gia Tiên",
    summary: "Hướng dẫn chi tiết từ nghệ nhân Đồ Đồng Lộc Nam về cách chọn bộ đỉnh đồng, lư hương, hạc thờ theo thước Lỗ Ban và tuổi mệnh gia chủ.",
    category: "BẠN CÓ BIẾT",
    date: "27/08/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/do-tho-cung.jpg",
    readTime: "5 phút đọc",
    keywords: ["đồ đồng nam định", "đồ đồng đẹp", "đồ thờ cúng bằng đồng", "đồ đồng lộc nam", "đỉnh đồng ý yên"],
    content: [
      "Trong văn hóa tâm linh người Việt, không gian thờ cúng gia tiên luôn là nơi linh thiêng, tôn nghiêm nhất của ngôi nhà. Việc lựa chọn đồ thờ cúng bằng đồng chuẩn xuất xứ từ làng nghề đúc đồng truyền thống Ý Yên, Nam Định không chỉ mang lại vẻ đẹp uy nghiêm mà còn tích tụ vượng khí, tài lộc cho gia đạo.",
      "### 1. Tại sao nên chọn đồ đồng Nam Định?",
      "Làng nghề đúc đồng Ý Yên – Nam Định với lịch sử hơn 900 năm được mệnh danh là cái nôi của nghệ thuật đúc đồng Việt Nam. Đồ Đồng Lộc Nam tại Nam Định sử dụng 100% phôi đồng đỏ, đồng catut thanh khiết, được nung chảy ở nhiệt độ trên 1200 độ C và đúc thủ công nguyên khối.",
      "Ưu điểm nổi bật của đồ đồng Nam Định:",
      "- Độ bền vĩnh cửu: Đồng thanh khiết không bị giòn, nứt hay bong tróc theo thời gian.",
      "- Hoa văn chạm khắc tinh xảo: Từng họa tiết Rồng chầu mặt nguyệt, Hoa sòi, Nghê vờn cầu được nghệ nhân chạm khắc tay sắc nét.",
      "- Màu sắc cổ kính, sang trọng: Được hun màu giả cổ hoặc mạ vàng 24k, dát vàng 9999 cao cấp.",
      "### 2. Chọn kích thước bộ đồ thờ theo thước Lỗ Ban",
      "Kích thước bộ đỉnh đồng (bộ tam sự, ngũ sự) cần tương xứng với kích thước bàn thờ gia tiên:",
      "- Bàn thờ dài 1m27 – 1m55: Phù hợp với bộ đỉnh đồng cao 45cm – 50cm.",
      "- Bàn thờ dài 1m75 – 1m97: Phù hợp với bộ ngũ sự cao 60cm – 65cm.",
      "- Bàn thờ dài trên 2m17 (từ đường, nhà thờ họ): Phù hợp với bộ ngũ sự cao 70cm trở lên.",
      "### 3. Địa chỉ mua đồ đồng đẹp uy tín",
      "Xưởng đúc Đồ Đồng Lộc Nam tự hào là đơn vị trực tiếp sản xuất và phân phối các mẫu đồ đồng đẹp, đồ thờ cúng cao cấp không qua trung gian. Quý khách hàng được kiểm tra hàng trước khi thanh toán và nhận phiếu bảo hành trọn đời chất lượng đồng."
    ]
  },
  {
    slug: "quy-trinh-duc-tuong-dong-chan-dung-truyen-than",
    title: "Quy Trình Đúc Đồng Chân Dung Truyền Thần Giống Thật 100% Của Xưởng Lộc Nam",
    summary: "Khám phá kỹ thuật đúc tượng chân dung ông bà, cha mẹ, danh nhân bằng đồng đỏ nguyên khối đạt độ giống và thần thái tới 99.9%.",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "26/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/4.jpg",
    readTime: "7 phút đọc",
    keywords: ["đúc đồng chân dung", "đúc tượng chân dung", "đồ đồng lộc nam", "tượng đồng nam định", "đúc tượng truyền thần"],
    content: [
      "Dịch vụ đúc đồng chân dung truyền thần để báo hiếu cha mẹ, tưởng nhớ tổ tiên hoặc tôn vinh các bậc tiền nhân, danh nhân lịch sử đang là xu hướng được nhiều gia đình và tổ chức lựa chọn.",
      "Tuy nhiên, đúc tượng chân dung là phân khúc khó nhất trong nghệ thuật đúc đồng vì đòi hỏi không chỉ tay nghề kỹ thuật mà còn phải truyền tải được cái thần, nét mặt và thần thái sống động của nhân vật.",
      "### Quy trình 5 bước đúc tượng chân dung tại Đồ Đồng Lộc Nam:",
      "1. Tạo mẫu đất sét (Khâu quan trọng nhất): Dựa trên hình ảnh chụp đa góc độ của nhân vật, điêu khắc gia đắp mẫu đất sét tỷ lệ 1:1. Khách hàng sẽ được xem trực tiếp hoặc duyệt qua video/ảnh để chỉnh sửa từng đường nét mắt, mũi, nụ cười đến khi ưng ý 100%.",
      "2. Làm khuôn thạch cao & khuôn composite: Chuyển mẫu đất sang khuôn âm bản chịu nhiệt đặc biệt để giữ nguyên từng chi tiết vi mô.",
      "3. Luyện đồng & Nấu đồng đỏ: Sử dụng đồng đỏ thanh khiết (đồng dây điện loại 1), pha tỷ lệ thiếc và kẽm chuẩn xác để dòng chảy đồng mịn và đều.",
      "4. Rót đồng vào khuôn: Nghệ nhân canh nhiệt độ rót đều tay, hạn chế tối đa bọt khí.",
      "5. Làm nguội, chạm tỉa & mạ dát vàng: Dũa gọt, chạm trổ từng sợi tóc, nếp nhăn và hoàn thiện bề mặt (phủ bóng nano, mạ vàng 24k hoặc dát vàng 9999).",
      "### Cam kết chất lượng từ Đồ Đồng Lộc Nam:",
      "Tất cả các sản phẩm đúc đồng chân dung tại xưởng Lộc Nam đều được bảo đảm độ giống thực tế, đúc liền khối vững chắc trường tồn cùng thời gian."
    ]
  },
  {
    slug: "top-mau-do-dong-dep-tinh-xao-nhat-nam-nay",
    title: "Top Các Mẫu Đồ Đồng Đẹp, Tinh Xảo Được Ưa Chuộng Nhất Năm Nay",
    summary: "Tổng hợp các kiệt tác đồ đồng mỹ nghệ: tượng Bác Hồ, tượng Trần Hưng Đạo, đỉnh đồng khảm ngũ sắc thất lân và tranh đồng mạ vàng.",
    category: "BẠN CÓ BIẾT",
    date: "25/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/bo-do-tho-ma-vang.jpg",
    readTime: "4 phút đọc",
    keywords: ["đồ đồng đẹp", "đồ đồng nam định", "đồ đồng lộc nam", "tượng đồng phong thủy", "bộ ngũ sự khảm ngũ sắc"],
    content: [
      "Thị trường mỹ nghệ ngày càng phát triển với nhiều sản phẩm đồng đúc cao cấp. Dưới đây là danh sách những mẫu đồ đồng đẹp được các gia chủ, doanh nhân và nhà sưu tầm săn đón nhiều nhất hiện nay:",
      "### 1. Bộ Ngũ Sự Khảm Ngũ Sắc Thất Lân Vờn Cầu",
      "Đỉnh đồng thất lân kết hợp đôi chân nến và đôi hạc thờ được khảm 5 kim loại quý: Vàng 9999, Bạc trắng, Đồng đỏ, Đồng xanh và Đồng đen. Từng đường khảm chìm sâu vào phôi đồng tạo nên hoa văn sống động và uy nghiêm trên ban thờ.",
      "### 2. Tượng Trần Quốc Tuấn Đồng Catut Cao Cấp",
      "Bức tượng Quốc Công Tiết Chế Hưng Đạo Đại Vương cầm hịch tướng sĩ đúc từ vỏ đạn quân sự (đồng catut) màu vàng ánh kim rực rỡ, mang năng lượng trấn trạch, trừ tà và đem lại uy quyền cho gia chủ.",
      "### 3. Tượng Bác Hồ Ngồi Ghế Mây Mạ Vàng 24K",
      "Tác phẩm tượng đồng chân dung Bác Hồ với thần thái ung dung, hiền từ là quà tặng ngoại giao và vật phẩm trang trọng hàng đầu tại các cơ quan, hội trường và phòng lưu niệm.",
      "### 4. Tranh Đồng Vinh Hoa Phú Quý 2m3 Mạ Vàng Dát Bạc",
      "Bức tranh phong cảnh cây tùng, chim hạc, hoa cúc, cuốn thư mang ý nghĩa cầu chúc tài lộc, gia đình sung túc, con cháu vinh hiển."
    ]
  },
  {
    slug: "y-nghia-phong-thuy-trong-dong-dong-son",
    title: "Ý Nghĩa Phong Thủy Trống Đồng Đông Sơn Trong Phòng Khách & Cơ Quan",
    summary: "Tại sao các doanh nhân thành đạt và cơ quan nhà nước luôn đặt trống đồng Đông Sơn tại vị trí trang trọng nhất?",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "24/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/locnam_trong_dong.jpg",
    readTime: "6 phút đọc",
    keywords: ["trống đồng đông sơn", "đồ đồng đẹp", "đồ đồng nam định", "quà tặng trống đồng", "đồ đồng lộc nam"],
    content: [
      "Trống đồng Đông Sơn không chỉ là bảo vật biểu tượng cho nền văn minh sông Hồng mà còn là vật phẩm phong thủy mang quyền năng trấn trạch và thu hút linh khí cực mạnh.",
      "### 1. Ý nghĩa biểu tượng của mặt trống đồng",
      "- Tâm trống (Mặt trời): Đại diện cho nguồn sống vô tận, ánh sáng xua tan tà khí và bóng tối, soi đường chỉ lối cho gia chủ hanh thông trong sự nghiệp.",
      "- Hình tượng chim Lạc bay ngược chiều kim đồng hồ: Tượng trưng cho dòng chảy thời gian và cội nguồn bất diệt của dân tộc Việt.",
      "- Cảnh sinh hoạt giã gạo, múa hát, chèo thuyền: Thể hiện sự ấm no, đoàn kết và sinh sôi nảy nở của tài lộc.",
      "### 2. Vị trí đặt trống đồng hợp phong thủy",
      "- Phòng khách: Đặt trên đôn gỗ cao 60cm – 80cm tại hướng Tây Bắc hoặc chính Bắc để kích hoạt tài vận.",
      "- Phòng làm việc / Phòng giám đốc: Đặt sau lưng bàn làm việc hoặc trên kệ tủ tài liệu tạo điểm tựa vững chắc, nâng cao uy quyền.",
      "- Phòng họp & Hội trường: Đặt mô hình trống đồng lớn ở trung tâm mang lại sự trang nghiêm và thịnh vượng bền lâu."
    ]
  },
  {
    slug: "cach-phan-biet-do-dong-that-va-dong-pha-tap-chat",
    title: "5 Cách Phân Biệt Đồ Đồng Thật và Đồng Pha Tạp Chất Đơn Giản Nhất",
    summary: "Cẩm nang bỏ túi giúp người mua không bị mắc bẫy đồng Đài Loan mạ màu hoặc đồng pha chì kém chất lượng.",
    category: "BẠN CÓ BIẾT",
    date: "23/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/artisan-foundry.jpg",
    readTime: "5 phút đọc",
    keywords: ["phân biệt đồ đồng", "đồ đồng nam định", "đồ đồng đẹp", "đồ đồng lộc nam", "mua đồ đồng uy tín"],
    content: [
      "Hiện nay trên thị trường có nhiều loại đồ đồng công nghiệp mạ xi mỏng hoặc đồng pha nhiều chì, kẽm chỉ sau 6 tháng đến 1 năm là bị bong tróc, xỉn đen không thể phục hồi.",
      "Dưới đây là 5 mẹo từ nghệ nhân xưởng Đồ Đồng Lộc Nam giúp bạn nhận biết ngay đồng thật chuẩn chất lượng:",
      "### 1. Kiểm tra bằng trọng lượng",
      "Đồ đồng thủ công Nam Định đúc bằng đồng thanh khiết thành dày bản nên cầm rất đầm tay, nặng hơn đáng kể so với đồ đồng dập máy công nghiệp mỏng rỗng ruột.",
      "### 2. Kiểm tra bằng âm thanh (tiếng chuông)",
      "Khi dùng thanh kim loại gõ nhẹ vào thân đỉnh đồng hoặc tượng đồng thật, âm thanh phát ra sẽ vang trầm, ấm và ngân dài. Trong khi đó đồng pha tạp chất hoặc đồng mỏng sẽ kêu cạch cạch đanh ngắn.",
      "### 3. Kiểm tra bằng lửa",
      "Đồng thật nguyên chất có nhiệt độ nóng chảy rất cao (> 1000°C). Khi hơ ngọn lửa gas vào bề mặt, đồng xịn không hề biến đổi màu hay bong tróc, chỉ cần lau nhẹ tàn khói là sáng bóng như mới.",
      "### 4. Kiểm tra đường nét hoa văn",
      "Đồ đồng thủ công mỹ nghệ có hoa văn chạm trổ thủ công mềm mại, sắc sảo từng milimet, không có vết ráp thô kệch hay ba-via lởm chởm như hàng đúc máy giá rẻ.",
      "### 5. Chọn cơ sở có cam kết bảo hành",
      "Hãy mua tại các xưởng đúc trực tiếp có thương hiệu như Đồ Đồng Lộc Nam – có địa chỉ xưởng rõ ràng tại làng nghề đúc đồng Ý Yên Nam Định và cam kết bảo hành trọn đời bằng văn bản."
    ]
  }
];
