export interface Article {
  slug: string;
  title: string;
  summary: string;
  category: string;
  date: string;
  author: string;
  image: string;
  readTime: string;
  keywords: string[];
  content: string[];
}

export const articlesData: Article[] = [
  {
    slug: "so-do-va-cach-sap-xep-ban-tho-gia-tien-chuan-phong-thuy-ngu-hanh",
    title: "Sơ Đồ & Cách Sắp Xếp Bàn Thờ Gia Tiên Chuẩn Phong Thủy Ngũ Hành Rước Tài Lộc",
    summary: "Cẩm nang hướng dẫn sơ đồ bài trí bàn thờ gia tiên chuẩn phong thủy ngũ hành từ nghệ nhân Lộc Nam: Vị trí đặt đỉnh đồng, đôi hạc, chân nến, bát hương, mâm bồng chuẩn nguyên tắc 'Đông bình Tây quả', 'Tiền lư Hậu đỉnh' giúp tụ khí sinh tài, gia đạo bình an.",
    category: "CẨM NANG PHONG THỦY",
    date: "14/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/locnam_bo_do_tho.jpg",
    readTime: "11 phút đọc",
    keywords: [
      "cách sắp xếp bàn thờ gia tiên",
      "sơ đồ bài trí bàn thờ gia tiên",
      "vị trí đặt đỉnh đồng hạc nến",
      "bàn thờ gia tiên chuẩn phong thủy",
      "bộ ngũ sự đặt như thế nào",
      "nguyên tắc đông bình tây quả",
      "đồ đồng lộc nam",
      "đồ thờ cúng nam định",
      "bài trí bàn thờ chuẩn phong thủy"
    ],
    content: [
      "Bàn thờ gia tiên là chốn tôn nghiêm kết nối cội nguồn, nơi con cháu bày tỏ lòng hiếu kính và tri ân các bậc tiền nhân. Trong phong thủy thờ cúng của người Việt, việc sắp xếp các vật phẩm thờ tự đúng phương vị không chỉ mang lại nét trang nghiêm, thanh tịnh cho không gian tâm linh mà còn giúp kích hoạt long mạch, tụ khí sinh tài, đem lại bình an và phú quý dài lâu cho toàn gia đạo.",
      "Tuy nhiên, không ít gia chủ khi thỉnh bộ đồ thờ bằng đồng về vẫn băn khoăn: Đỉnh đồng nên đặt trước hay sau bát hương? Đôi hạc chầu quay hướng nào? Bình hoa và mâm quả sắp xếp ra sao cho đúng quy luật 'Đông bình Tây quả'?",
      "Bài viết dưới đây từ các nghệ nhân kỳ cựu của Xưởng Đúc Đồng Lộc Nam (Ý Yên, Nam Định) sẽ cung cấp sơ đồ bài trí chuẩn mực, phân tích quy luật ngũ hành và các nguyên tắc phong thủy giúp gia chủ an tâm sắp đặt trọn vẹn chốn thờ tự linh thiêng.",
      "## PHẦN 1: QUY TẮC NGŨ HÀNH TƯƠNG SINH TRÊN BÀN THỜ GIA TIÊN",
      "Một không gian thờ cúng chuẩn mực cần hội tụ đủ 5 yếu tố Ngũ Hành (Kim - Mộc - Thủy - Hỏa - Thổ) tương sinh, hỗ trợ lẫn nhau:",
      "- Hành Kim: Đại diện bởi bộ đồ thờ bằng đồng (đỉnh đồng, đôi hạc, chân nến, mâm bồng, ống hương bằng đồng). Kim mang tính bền vững, sáng ngời, tượng trưng cho sự trường tồn và phúc lộc dồi dào.",
      "- Hành Mộc: Đại diện bởi bàn thờ bằng gỗ tự nhiên (gỗ mít, gỗ gụ, gỗ hương) hoặc bài vị, đũa thờ gỗ.",
      "- Hành Thủy: Đại diện bởi chén nước, chén rượu thanh tịnh đặt trên kỷ ngai thờ và bình hoa tươi chứa nước.",
      "- Hành Hỏa: Đại diện bởi ánh lửa đèn dầu, nến thắp hoặc nén hương trầm đỏ ấm cúng khi hành lễ.",
      "- Hành Thổ: Đại diện bởi tro nếp thơm hoặc cát phong thủy trong lòng bát hương, kết hợp với các bình hoa sứ hoặc đồ đất nung.",
      "> Lưu ý của nghệ nhân: Khi ngũ hành cân bằng, dương khí và âm khí hòa hợp, bàn thờ sẽ trở thành tụ điểm năng lượng tốt nhất trong ngôi nhà, che chở mọi thành viên khỏi tà khí và vận xui.",
      "## PHẦN 2: SƠ ĐỒ BỐ TRÍ BÀN THỜ THEO 3 TẦNG CHIỀU SÂU 'TIỀN - TRUNG - HẬU'",
      "Để bàn thờ có chiều sâu uy nghiêm và thuận tiện cho việc thắp hương, dâng lễ, không gian bàn thờ được phân chia theo 3 lớp chính:",
      "### 1. Tầng Hậu (Lớp Trong Cùng Sát Vách Bàn Thờ)",
      "- Ngai thờ / Khám thờ / Bài vị gia tiên: Đặt tại vị trí cao nhất chính giữa, sát tường gỗ hoặc bức vách phòng thờ.",
      "- Đỉnh đồng (Lư hương lớn): Đặt chính giữa bàn thờ, ngay phía trước khám thờ hoặc bài vị. Nắp đỉnh đồng có con Nghê uy nghi quay đầu nhìn thẳng ra phía trước để trấn áp hung khí và canh giữ long mạch gia trạch.",
      "- Đôi Hạc đồng cưỡi kim quy: Đặt đối xứng hai bên đỉnh đồng, mỏ hạc ngậm cành hoa sen hướng chầu vào đỉnh thờ. Khoảng cách giữa thân đỉnh và hạc từ 5cm đến 10cm tùy kích thước bàn thờ.",
      "### 2. Tầng Trung (Lớp Ở Giữa)",
      "- Đôi chân nến bằng đồng: Đặt ở hai góc phía ngoài của đôi hạc, hơi chếch về mép ngoài bàn thờ. Chân nến bên trái tượng trưng cho hành Dương (Mặt Trời), chân nến bên phải tượng trưng cho hành Âm (Mặt Trăng), thể hiện nhật nguyệt chiếu rọi tâm can con cháu.",
      "- Bát hương (Pháp bảo cốt lõi): Đặt tại vị trí trung tâm, phía trước đỉnh đồng. Khoảng cách từ đỉnh đồng đến bát hương cần đủ rộng (khoảng 10cm - 15cm) để gia chủ dễ dàng cắm hương mà không bị vướng.",
      "- Cách bài trí 3 bát hương chuẩn: Bát hương thờ Thần Linh ngự ở giữa (kích thước to nhất và kê cao nhất). Bát hương thờ Gia Tiên đặt bên tay phải (theo hướng người đứng cúng nhìn vào). Bát hương thờ Bà Cô Tổ, Ông Mãnh đặt bên tay trái.",
      "### 3. Tầng Tiền (Lớp Phía Trước Mép Ngoài Cùng Bàn Thờ)",
      "- Mâm bồng (Đĩa đựng hoa quả, ngũ quả): Đặt phía trước bát hương, cách mép bàn thờ khoảng 5cm.",
      "- Kỷ ngai chén thờ (3 chén hoặc 5 chén): Đặt ở vị trí trước mâm bồng, ngay mép ngoài cùng bàn thờ, dùng để dâng nước thanh tịnh và rượu lễ.",
      "- Đôi đèn dầu thờ hoặc đèn thờ quả dứa bằng đồng: Đặt ở hai góc mép ngoài cùng bàn thờ để thắp sáng không gian.",
      "- Bình hoa & Ống hương: Bày đối xứng hai bên hồi bàn thờ theo nguyên tắc 'Đông bình Tây quả'.",
      "## PHẦN 3: 4 NGUYÊN TẮC PHONG THỦY 'BẤT DI BẤT DỊCH' KHI BÀY BÀN THỜ",
      "### 1. Nguyên Tắc 'Đông Bình Tây Quả'",
      "- Xuất xứ từ quy luật tự nhiên: Mặt trời mọc ở đằng Đông (hoa nở sinh sôi) và lặn ở đằng Tây (kết trái ngọt ngào).",
      "- Khi gia chủ đứng hướng mặt vào bàn thờ: Bình hoa đặt ở phía bên tay trái (phía Đông), mâm ngũ quả đặt ở phía bên tay phải (phía Tây) để đón lộc từ đất trời.",
      "### 2. Nguyên Tắc 'Tiền Lư Hậu Đỉnh'",
      "- Quy tắc truyền thống chuẩn mực nhất hiện nay: Đỉnh đồng đặt ở phía sau, Bát hương đặt ở phía trước. Ưu điểm của cách bố trí này là tạo thế tựa vững chãi của đỉnh đồng che chở phía sau, đồng thời gia chủ cắm hương hàng ngày dễ dàng, không lo bị bỏng hoặc vướng tay vào nắp nghê.",
      "### 3. Nguyên Tắc Cân Bằng 'Tả Thanh Long – Hữu Bạch Hổ'",
      "- Phía bên trái bàn thờ (Thanh Long): Bày các vật phẩm cao và mang tính dương như bình hoa đồng cỡ lớn hoặc chân nến cao.",
      "- Phía bên phải bàn thờ (Bạch Hổ): Bày các vật phẩm thấp và mang tính tĩnh như đĩa trầu cau hoặc mâm bồng vừa phải.",
      "### 4. Bát Hương Tuyệt Đối Bất Di Bất Dịch",
      "- Bát hương là điểm hội tụ khí thiêng của gia tiên. Khi đã làm lễ an vị thì tuyệt đối không được xê dịch vị trí tùy tiện.",
      "- Khi bao sái ban thờ ngày Tết hoặc ngày giỗ chạp, dùng một tay giữ chặt thân bát hương, tay kia dùng khăn mềm nhúng rượu gừng lau nhẹ nhàng xung quanh.",
      "## PHẦN 4: BẢNG TRA KÍCH THƯỚC BÀN THỜ & BỘ ĐỒ THỜ BẰNG ĐỒNG THEO THƯỚC LỖ BAN",
      "Chọn bộ đồ thờ tương xứng với kích thước ban thờ là điều kiện tiên quyết để đạt cung phong thủy tốt lành:",
      "- Bàn thờ dài 1m27 đến 1m55 (Sâu 61cm - 69cm): Thích hợp với bộ đỉnh đồng cao 45cm (Cung Tiến Bảo). Nên chọn bộ Tam Sự để không gian thông thoáng.",
      "- Bàn thờ dài 1m75 đến 1m97 (Sâu 81cm - 97cm): Kích thước bàn thờ chuẩn nhất của đa số gia đình Việt. Thích hợp bài trí trọn bộ Ngũ Sự đồng cao 50cm hoặc 60cm (Cung Đăng Khoa, Thêm Đinh, Tài Lộc).",
      "- Bàn thờ dài 1m97 đến 2m17 (Sâu 97cm - 107cm): Thích hợp bài trí bộ Ngũ Sự cao 65cm hoặc 70cm đúc đồng đỏ hoặc đồng cát tút uy nghi.",
      "- Nhà thờ họ, Từ đường (Bàn thờ dài trên 2m17): Bày bộ đỉnh 70cm trở lên kết hợp đôi hạc chầu đứng sàn cao 1m60 đến 1m80 và bộ hoành phi câu đối đồng chạm tay.",
      "## PHẦN 5: NHỮNG ĐIỀU ĐẠI KỴ CẦN TRÁNH KHI SẮP XẾP BÀN THỜ GIA TIÊN",
      "- Không đặt bàn thờ đối diện thẳng cửa nhà vệ sinh, nhà tắm hoặc ngay dưới xà ngang trần nhà.",
      "- Không đặt bàn thờ trong phòng ngủ hoặc nơi ẩm thấp, thiếu ánh sáng tự nhiên.",
      "- Không để hoa héo, lá khô hoặc trái cây giả bằng nhựa trên bàn thờ gia tiên lâu ngày.",
      "- Đồ đồng thờ cúng cần giữ sạch sẽ, định kỳ lau bằng khăn khô mềm để bề mặt luôn sáng đẹp tôn nghiêm.",
      "## PHẦN 6: ĐỒ ĐỒNG LỘC NAM – ĐỊA CHỈ TƯ VẤN & CUNG CẤP ĐỒ THỜ TẬN XƯỞNG Ý YÊN",
      "Xưởng Đúc Đồng Lộc Nam với đội ngũ nghệ nhân truyền thống làng nghề Ý Yên - Nam Định luôn sẵn sàng khảo sát, đo đạc và tư vấn trực tiếp sơ đồ bài trí bàn thờ gia tiên chuẩn thước Lỗ Ban theo mệnh gia chủ hoàn toàn miễn phí.",
      "- Địa chỉ xưởng: Cụm Công Nghiệp Làng Nghề Đúc Đồng Ý Yên, Tỉnh Nam Định.",
      "- Hotline tư vấn phong thủy 24/7: 0846 699 997 – 0836 122 222",
      "- Website chính thức: https://www.quatanglocnam.com",
      "- Chính sách: Giao hàng tận nhà, kiểm tra hàng đúng chất lượng đồng đỏ nguyên chất mới thanh toán, bảo hành trọn đời."
    ]
  },
  {
    slug: "bao-gia-duc-tuong-chan-dung-bang-dong-truyen-than-2026",
    title: "Báo Giá Đúc Tượng Chân Dung Bằng Đồng Truyền Thần 2026: Bảng Giá Xưởng & Quy Trình Đắp Mẫu Ý Yên",
    summary: "Bảng báo giá chi tiết dịch vụ đúc tượng chân dung ông bà, cha mẹ, danh nhân bằng đồng đỏ nguyên khối tận xưởng Ý Yên Nam Định năm 2026. Quy trình đắp mẫu đất sét 1:1, cam kết truyền thần giống trên 99%, duyệt mẫu trực tiếp trước khi rót đồng.",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "13/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/tuong_chan_dung/tuong_cd_01.jpg",
    readTime: "9 phút đọc",
    keywords: [
      "báo giá đúc tượng chân dung bằng đồng",
      "đúc tượng truyền thần giá bao nhiêu",
      "đúc tượng bố mẹ ông bà",
      "đúc tượng chân dung nam định",
      "giá đúc tượng đồng đỏ",
      "quy trình đắp mẫu tượng chân dung",
      "đồ đồng lộc nam",
      "đúc tượng đồng ý yên"
    ],
    content: [
      "Đúc tượng đồng chân dung truyền thần (đúc tượng ông bà, cha mẹ, tiền nhân hoặc danh nhân lịch sử) là nét đẹp văn hóa thể hiện tấm lòng hiếu đạo 'Uống nước nhớ nguồn' sâu sắc của con cháu. Khác với những bức ảnh thờ có thể phai mờ theo năm tháng, một pho tượng chân dung bằng đồng đỏ nguyên khối có tuổi thọ trường tồn hàng trăm năm, lưu giữ trọn vẹn nét mặt, nụ cười và thần thái phúc hậu của người thân cho muôn đời sau.",
      "Tuy nhiên, đúc tượng chân dung là phân khúc đỉnh cao và khó nhất trong nghệ thuật đúc đồng. Rất nhiều gia đình thắc mắc: Chi phí đúc tượng chân dung truyền thần hiện nay là bao nhiêu? Cần chuẩn bị những tư liệu gì? Làm sao để đảm bảo tượng đúc ra giống người thật?",
      "Xưởng Đúc Đồng Lộc Nam xin gửi tới quý gia chủ bảng báo giá chi tiết tận xưởng năm 2026 cùng quy trình đắp mẫu đất nghiêm ngặt cam kết độ giống trên 99%.",
      "## PHẦN 1: BẢNG BÁO GIÁ ĐÚC TƯỢNG CHÂN DUNG ĐỒNG ĐỎ NGUYÊN KHỐI 2026",
      "Tại Xưởng Đúc Đồng Lộc Nam, 100% tượng chân dung được đúc từ phôi Đồng Đỏ thanh khiết (sử dụng dây cáp điện đỏ tuyển chọn loại 1). Dưới đây là bảng giá niêm yết tại xưởng không qua trung gian:",
      "### 1. Bảng Giá Tượng Chân Dung Bán Thân (Đầu & Ngực Có Bệ Chữ)",
      "- Tượng bán thân cao 38cm - 40cm (nặng ~12kg - 14kg): Giá từ 14.500.000đ – 16.000.000đ / pho.",
      "- Tượng bán thân cao 45cm - 48cm (nặng ~15kg - 18kg, kích thước phổ biến nhất trên ban thờ): Giá từ 17.500.000đ – 20.000.000đ / pho.",
      "- Tượng bán thân cao 60cm (nặng ~25kg - 28kg, thích hợp từ đường, nhà thờ họ): Giá từ 24.000.000đ – 27.000.000đ / pho.",
      "- Tượng bán thân cao 70cm - 80cm: Giá từ 30.000.000đ – 38.000.000đ / pho.",
      "### 2. Tùy Chọn Hoàn Thiện Bề Mặt & Mạ Dát Vàng Cao Cấp",
      "- Làm màu đồng mộc hoặc hun màu cánh gián giả cổ, phủ nano 2K bảo vệ: Miễn phí theo gói tiêu chuẩn.",
      "- Dát Vàng Ròng 9999 / Vàng Ta chuẩn tuổi: Cộng thêm từ 5.000.000đ – 12.000.000đ / pho tùy kích thước (có chứng thư cam kết vàng thật).",
      "- Mạ vàng điện phân 24k sáng bóng: Cộng thêm từ 6.500.000đ – 14.000.000đ / pho.",
      "### 3. Tượng Toàn Thân & Tượng Tỷ Lệ 1:1 Người Thật",
      "- Tượng chân dung toàn thân ngồi ghế bành / ngai rồng (cao 81cm, 107cm, 127cm): Giá từ 45.000.000đ – 90.000.000đ tùy trọng lượng và chi tiết hoa văn.",
      "- Tượng đứng toàn thân kích thước thực tế: Khảo sát và lên báo giá dự toán thiết kế riêng.",
      "> Lưu ý: Báo giá đã bao gồm trọn gói: Chi phí điêu khắc gia đắp mẫu đất sét, chỉnh sửa mẫu đất đến khi ưng ý, phôi đồng đỏ nguyên khối, gia công nguội chạm khắc tên tuổi ngày mất lên bệ tượng, đóng thùng xốp gỗ và vận chuyển tận nhà trên toàn quốc.",
      "## PHẦN 2: 4 YẾU TỐ QUYẾT ĐỊNH GIÁ TRỊ VÀ ĐỘ GIỐNG CỦA TƯỢNG ĐỒNG CHÂN DUNG",
      "### 1. Trình Độ Của Điêu Khắc Gia Đắp Mẫu Đất (Yếu Tố Cốt Tử 70%)",
      "Đúc tượng chân dung không thể dùng máy móc hay công nghệ 3D quét rập khuôn mà phụ thuộc hoàn toàn vào 'đôi bàn tay vàng' và con mắt thẩm mỹ của điêu khắc gia. Một nghệ nhân giỏi không chỉ tạc lại các đường nét nhân học (sống mũi, gò má, đôi mắt) mà còn phải bắt được 'cái thần' – ánh nhìn ấm áp, khóe miệng tươi tắn của nhân vật.",
      "### 2. Chất Liệu Đúc: Đồng Đỏ Thanh Khiết Tuyển Chọn",
      "Đồ Đồng Lộc Nam cam kết nói KHÔNG với đồng phế liệu hay đồng pha tạp chất. Đồng đỏ cáp điện nguyên chất có độ dẻo và độ chảy lỏng tối ưu ở 1.200°C, giúp dòng kim loại chảy tới từng nếp nhăn nhỏ nhất và sợi tóc mai, mang lại bề mặt tượng mịn màng, không bị rỗ xỉ hay giòn vỡ.",
      "### 3. Quy Trình Khách Hàng Trực Tiếp Duyệt Mẫu Đất",
      "Khác với các xưởng đúc thương mại tự ý đúc rồi ép khách nhận hàng, tại Lộc Nam, sau khi đắp mẫu đất xong, xưởng sẽ mời gia đình đến xưởng duyệt trực tiếp hoặc quay video góc xoay 360 độ độ nét cao. Điêu khắc gia sẽ lắng nghe ý kiến của từng người thân để điều chỉnh mắt, sống mũi, khóe cười cho tới khi gia đình hoàn toàn gật đầu mới chuyển sang khâu đổ khuôn đúc đồng.",
      "### 4. Kỹ Thuật Chạm Khắc Nguội Sau Khi Đúc",
      "Khi dỡ khuôn đất, pho tượng thô sẽ được các nghệ nhân kim hoàn dùng đục thép tỉ mỉ chạm gọt từng sợi lông mày, nếp áo và con ngươi mắt, tạo nên chiều sâu sống động như thật.",
      "## PHẦN 3: QUY TRÌNH 6 BƯỚC ĐÚC TƯỢNG CHÂN DUNG TẠI XƯỞNG LỘC NAM",
      "- Bước 1 (Tiếp nhận tư liệu): Khách hàng gửi ảnh chụp nhân vật (ảnh thẻ, ảnh chụp kỷ niệm, ảnh chụp nghiêng góc 45 độ và góc 90 độ nếu có) kèm mô tả đặc điểm nhận dạng đặc trưng.",
      "- Bước 2 (Đắp mẫu đất sét 1:1): Điêu khắc gia tốt nghiệp Đại học Mỹ Thuật tạo hình mẫu đất sét trong 5-7 ngày.",
      "- Bước 3 (Chỉnh sửa và duyệt mẫu): Gia đình thẩm định mẫu đất, góp ý chỉnh sửa chi tiết. Lộc Nam chỉ tiến hành đúc khi khách hàng duyệt mẫu 100%.",
      "- Bước 4 (Tạo khuôn thạch cao & làm khuôn đồng âm dương): Đổ khuôn thạch cao bảo lưu chi tiết mẫu đất, sau đó trát đất sét chịu nhiệt và nung chín khuôn trong lò.",
      "- Bước 5 (Nấu và rót đồng đỏ): Đun nóng chảy đồng đỏ cáp điện ở nhiệt độ 1.200°C và rót vào khuôn liền mạch.",
      "- Bước 6 (Làm nguội, chạm tỉa & phủ nano 2K): Nghệ nhân sửa nguội, chạm khắc thông tin lên bệ tượng, làm màu theo yêu cầu và phủ bóng bảo vệ.",
      "## PHẦN 4: KHÁCH HÀNG CẦN CHUẨN BỊ GÌ TRƯỚC KHI ĐẶT ĐÚC TƯỢNG?",
      "- Tư liệu ảnh: Cung cấp ảnh rõ nét nhất có thể. Nếu chỉ có ảnh cũ chụp đen trắng thời bao cấp mờ, nghệ nhân giàu kinh nghiệm của Lộc Nam vẫn có thể dựng lại dựa trên tư vấn trực tiếp từ con cháu.",
      "- Thời gian đặt hàng: Toàn bộ quá trình từ đắp mẫu đến bàn giao tượng đồng hoàn thiện thường mất từ 20 đến 30 ngày. Gia đình chuẩn bị làm lễ mừng thọ, khánh thành từ đường hoặc lễ giỗ nên đặt trước tối thiểu 1 tháng.",
      "## PHẦN 5: CHÍNH SÁCH CAM KẾT VÀNG TỪ ĐỒ ĐỒNG LỘC NAM",
      "- Cam kết thần thái: Tượng đạt độ giống và thần thái trên 99% so với mẫu đất đã được gia đình phê duyệt.",
      "- Cam kết chất liệu: Đền tiền gấp 10 lần nếu phát hiện đồng pha chì hoặc đồng tạp chất kém chất lượng.",
      "- Bảo hành: Bảo hành chất lượng đồng vĩnh cửu trọn đời.",
      "- Giao hàng: Miễn phí vận chuyển toàn quốc, kiểm tra tượng tận tay mới thanh toán.",
      "## LIÊN HỆ ĐẶT ĐÚC TƯỢNG TRUYỀN THẦN",
      "- Xưởng chính: Làng Nghề Đúc Đồng Truyền Thống Ý Yên, Tỉnh Nam Định.",
      "- Hotline / Zalo tư vấn nghệ nhân: 0846 699 997 – 0836 122 222",
      "- Website: https://www.quatanglocnam.com"
    ]
  },
  {
    slug: "5-cach-danh-bong-lam-sang-do-dong-bi-xin-mau-tai-nha",
    title: "5 Cách Đánh Bóng Làm Sáng Đồ Đồng Bị Xỉn Màu Tại Nhà Đơn Giản, Hiệu Quả 100% Không Làm Hại Bề Mặt",
    summary: "Hướng dẫn 5 mẹo dân gian và phương pháp chuyên nghiệp giúp làm sạch lư hương, đỉnh đồng, chân nến bị hoen gỉ, ố đen bằng nguyên liệu tự nhiên quen thuộc: chanh tươi, giấm ăn, baking soda, kem đánh răng. Đảm bảo đồ thờ sáng bóng như mới đón tài lộc.",
    category: "BẠN CÓ BIẾT",
    date: "13/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/bo-do-tho-ma-vang.jpg",
    readTime: "8 phút đọc",
    keywords: [
      "cách đánh bóng đồ đồng",
      "làm sáng đồ đồng bị xỉn màu",
      "cách tẩy đồ đồng tại nhà",
      "đánh bóng lư hương đồng",
      "mẹo làm mới đồ thờ bằng đồng",
      "tẩy rỉ đồng xanh",
      "đồ đồng lộc nam",
      "vệ sinh bộ đỉnh đồng gia tiên"
    ],
    content: [
      "Sau nhiều năm ngự trên bàn thờ gia tiên, chịu ảnh hưởng từ khói hương, tàn nhang, độ ẩm không khí và bụi bẩn, các vật phẩm đồ đồng như đỉnh đồng, lư hương, đôi hạc, chân nến thường xuất hiện tình trạng xỉn màu, ố đen hoặc xuất hiện các vệt ố xanh (gỉ đồng). Điều này khiến không gian thờ cúng giảm bớt vẻ trang nghiêm, sáng đẹp vốn có.",
      "Nhiều gia chủ muốn tự tay bao sái, làm mới bộ đồ thờ tại nhà dịp cuối năm, ngày giỗ chạp nhưng lo sợ dùng sai hóa chất sẽ làm ăn mòn hoặc làm hỏng lớp hoa văn chạm trổ thủ công quý giá.",
      "Đừng lo lắng! Nghệ nhân Đồ Đồng Lộc Nam xin chia sẻ 5 công thức đánh bóng đồ đồng bị xỉn màu tại nhà cực kỳ đơn giản, an toàn bằng các nguyên liệu tự nhiên sẵn có trong gian bếp, hiệu quả sáng bóng đạt 100% ngay từ lần đầu tiên.",
      "## NGUYÊN NHÂN KHIẾN ĐỒ ĐỒNG BỊ XỈN MÀU & NGUYÊN TẮC CẦN BIẾT",
      "Về mặt khoa học, đồng là kim loại có phản ứng oxy hóa chậm với oxy trong không khí, khí CO2 và độ ẩm, tạo thành lớp oxit đồng (CuO màu đen hoặc Cu2(OH)2CO3 màu xanh xám). Đây là hiện tượng vật lý hoàn toàn tự nhiên của đồng nguyên chất.",
      "> CẢNH BÁO QUAN TRỌNG: Các phương pháp tẩy sáng dưới đây CHỈ áp dụng cho đồ đồng vàng, đồng đỏ nguyên mộc cần lấy lại màu vàng sáng bóng. TUYỆT ĐỐI KHÔNG áp dụng cho đồ đồng khảm tam khí, khảm ngũ sắc hoặc đồ đồng hun rêu giả cổ cao cấp, vì các chất có tính axit sẽ làm bay màu lớp hun nghệ thuật.",
      "## 5 CÁCH ĐÁNH BÓNG ĐỒ ĐỒNG TẠI NHÀ HIỆU QUẢ NHẤT",
      "### Cách 1: Sử Dụng Chanh Tươi & Muối Hạt (Phương Pháp Dân Gian An Toàn Nhất)",
      "Axit citric tự nhiên trong quả chanh kết hợp với tính mài mòn nhẹ của muối biển là 'khắc tinh' của các mảng bám oxy hóa trên bề mặt đồng.",
      "- Nguyên liệu: 2 - 3 quả chanh tươi mọng nước, 1 bát muối hạt giã mịn, khăn mềm hoặc miếng mút rửa bát.",
      "- Các bước thực hiện:",
      "- Bước 1: Cắt đôi quả chanh, chấm trực tiếp mặt cắt vào bát muối hạt.",
      "- Bước 2: Chà nhẹ nhàng lên bề mặt đỉnh đồng hoặc chân nến theo hình xoắn ốc. Nước cốt chanh và muối sẽ phản ứng làm tan lớp oxit đồng đen xỉn chỉ sau 1-2 phút.",
      "- Bước 3: Dùng bàn chải đánh răng lông mềm chà nhẹ vào các khe kẽ hoa văn rồng chầu, mây lượn để lấy đi vết bẩn cứng đầu.",
      "- Bước 4: Rửa sạch lại bằng nước ấm và dùng khăn cotton khô lau thật ráo nước.",
      "### Cách 2: Dùng Hỗn Hợp Giấm Ăn & Bột Mì (Công Thức 'Kem Tẩy' Cổ Truyền)",
      "Giấm ăn (axit axetic) hòa quyện cùng bột mì tạo thành một lớp bùn dính giữ axit trên bề mặt kim loại lâu hơn mà không bị chảy nhỏ giọt.",
      "- Nguyên liệu: 1 bát bột mì đa dụng, 2 thìa canh giấm trắng, 1 thìa muối tinh.",
      "- Các bước thực hiện:",
      "- Bước 1: Trộn đều bột mì, giấm và muối để tạo thành hỗn hợp sền sệt dạng bột nhão.",
      "- Bước 2: Dùng cọ quét đều lớp bột này lên toàn bộ thân đỉnh đồng, chân hạc và bát hương.",
      "- Bước 3: Để yên trong khoảng 15 - 20 phút cho hỗn hợp khô lại và hút sạch các tạp chất oxy hóa.",
      "- Bước 4: Dùng khăn ấm lau sạch lớp bột mì khô. Bạn sẽ thấy phôi đồng bên dưới bừng sáng như vừa xuất xưởng!",
      "### Cách 3: Sử Dụng Baking Soda (Muối Nở) & Nước Cốt Chanh",
      "Phản ứng sủi bọt khí CO2 giữa baking soda kiềm nhẹ và chanh axit tạo ra hàng triệu bọt vi mô len lỏi vào các chi tiết hoa văn chạm âm bản sâu nhất.",
      "- Nguyên liệu: 2 thìa bột baking soda, nước cốt 1 quả chanh.",
      "- Các bước thực hiện:",
      "- Bước 1: Cho baking soda vào chén nhỏ, từ từ đổ nước cốt chanh vào cho đến khi hỗn hợp sủi bọt tạo thành chất kem sánh mịn.",
      "- Bước 2: Dùng khăn mềm hoặc bàn chải thấm kem này thoa đều lên bề mặt đồ đồng.",
      "- Bước 3: Chà nhẹ tay trong 3 - 5 phút, tập trung vào những vị trí bị gỉ xanh hoặc hoen ố đen.",
      "- Bước 4: Rửa lại bằng nước sạch và dùng máy sấy tóc sấy khô hoàn toàn các ngóc ngách.",
      "### Cách 4: Sử Dụng Kem Đánh Răng Thông Dụng",
      "Trong kem đánh răng có chứa các hạt siêu mịn silica và chất làm sạch, rất thích hợp để đánh bóng các vật phẩm đồ đồng nhỏ như đài sen, chén nước, thìa trầm hương mà không lo bị xước.",
      "- Các bước thực hiện:",
      "- Bước 1: Bôi một lượng kem đánh răng vừa đủ lên bề mặt đồ đồng.",
      "- Bước 2: Dùng khăn ẩm hoặc bàn chải mềm xoa đều và miết nhẹ theo chiều hoa văn.",
      "- Bước 3: Sau khoảng 5 phút, rửa sạch bằng nước ấm và lau khô ráo.",
      "### Cách 5: Sử Dụng Kem Đánh Bóng Chuyên Dụng Autosol Hoặc Cana",
      "Đối với những bộ đồ đồng cổ để lâu năm bị rỉ đồng xanh bám kết dày bản, các nguyên liệu tự nhiên có thể mất nhiều thời gian. Khi đó, kem đánh bóng kim loại Autosol là giải pháp chuyên nghiệp tối ưu.",
      "- Cách làm: Lấy một lượng nhỏ kem Autosol chấm lên bề mặt đồng, dùng khăn nỉ hoặc vải thô chà miết dứt khoát. Bụi bẩn và rỉ đồng sẽ bám đen vào khăn, trả lại bề mặt đồng ánh kim sáng loáng như gương soi.",
      "## BÍ QUYẾT GIỮ ĐỒ ĐỒNG LUÔN SÁNG BÓNG TRÊN 10 NĂM KHÔNG BỊ Ố LẠI",
      "Sau khi làm sạch đồ đồng xong, khâu bảo quản là yếu tố quyết định đồ đồng có giữ được độ bóng lâu dài hay không:",
      "- Lau khô tuyệt đối: Sau khi rửa nước, phải lau khô kiệt nước và dùng máy sấy tóc hong khô mọi ngách nhỏ trước khi an vị lên bàn thờ. Nước đọng chính là thủ phạm gây rỉ xanh nhanh nhất.",
      "- Phủ lớp sáp bảo vệ: Có thể dùng một chút sáp ong mỏng hoặc dầu khoáng xoa đều lên bề mặt đồ đồng để tạo màng ngăn không khí tiếp xúc với kim loại.",
      "- Tránh chạm tay trần: Mồ hôi tay chứa muối và axit là tác nhân hàng đầu gây loang ố bề mặt đồng. Khi bưng bê, gia chủ nên dùng găng tay vải mỏng hoặc khăn mềm.",
      "## KHI NÀO NÊN GỬI BỘ ĐỒ THỜ VỀ XƯỞNG ĐÚC ĐỒNG LỘC NAM?",
      "Nếu bộ đồ thờ của gia đình bạn là dòng đồ đồng hun rêu, đồng khảm tam khí - ngũ sắc cổ truyền, hoặc bề mặt đã bị xước sâu theo năm tháng, việc tự tẩy tại nhà có thể làm mất đi giá trị thẩm mỹ. Hãy liên hệ với Xưởng Đúc Đồng Lộc Nam để được phục hồi, hun màu cổ kính và phủ lớp sơn bóng Nano 2K bảo hành trường tồn hàng chục năm.",
      "- Hotline tư vấn bảo quản đồ đồng: 0846 699 997 – 0836 122 222",
      "- Xưởng sản xuất: Làng Nghề Đúc Đồng Ý Yên, Tỉnh Nam Định.",
      "- Website: https://www.quatanglocnam.com"
    ]
  },
  {
    slug: "cam-nang-chon-mua-bo-do-tho-bang-dong-y-yen-nam-dinh",
    title: "Cẩm Nang Chọn Mua Bộ Đồ Thờ Bằng Đồng Ý Yên Nam Định: Phân Biệt Chất Liệu, Thước Lỗ Ban & Bảng Giá Xưởng 2026",
    summary: "Hướng dẫn toàn diện từ nghệ nhân xưởng đúc Lộc Nam: Cấu tạo bộ tam sự ngũ sự, phân biệt 4 loại đồng (đồng đỏ, đồng vàng, cát tút, mạ vàng 24k), bảng tra thước Lỗ Ban 38.8cm và báo giá tận xưởng không qua trung gian.",
    category: "CẨM NANG PHONG THỦY",
    date: "12/09/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/locnam_dinh_dong.jpg",
    readTime: "12 phút đọc",
    keywords: [
      "bộ đồ thờ bằng đồng",
      "đồ thờ cúng nam định",
      "đồ đồng lộc nam",
      "đỉnh đồng ý yên",
      "bộ ngũ sự bằng đồng",
      "báo giá đồ thờ bằng đồng",
      "thước lỗ ban bàn thờ",
      "đồ đồng đẹp nam định",
      "phân biệt đồng đỏ đồng thau",
      "cách bày bàn thờ gia tiên"
    ],
    content: [
      "Trong văn hóa tâm linh của người Việt, không gian thờ cúng gia tiên là nơi tôn nghiêm nhất trong mỗi gia đình, thể hiện lòng hiếu kính 'Uống nước nhớ nguồn' đối với tổ tiên, cội nguồn. Trong đó, bộ đồ thờ bằng đồng luôn là lựa chọn hàng đầu của các gia đình danh gia, quyền quý bởi vẻ đẹp uy nghiêm, độ bền trường tồn hàng trăm năm và ý nghĩa phong thủy hội tụ linh khí ngũ hành.",
      "Tuy nhiên, trước sự xuất hiện tràn lan của các dòng đồng pha chì, đồng Đài Loan dập máy mạ xi mỏng chỉ sau vài năm là xỉn ố, việc tìm mua được một bộ đồ thờ bằng đồng chuẩn làng nghề Ý Yên Nam Định nguyên chất, đúc thủ công tinh xảo là nỗi băn khoăn của rất nhiều gia chủ.",
      "Bài viết cẩm nang dưới đây của Xưởng Đúc Đồng Lộc Nam sẽ cung cấp cho bạn cái nhìn toàn diện từ cấu tạo bộ tam sự - ngũ sự, cách phân biệt các loại đồng, bảng tra kích thước theo thước Lỗ Ban và bảng báo giá chi tiết tận xưởng năm 2026.",
      "## PHẦN 1: CẤU TẠO BỘ ĐỒ THỜ BẰNG ĐỒNG GỒM NHỮNG GÌ? PHÂN BIỆT BỘ TAM SỰ VÀ BỘ NGŨ SỰ",
      "Tùy thuộc vào diện tích bàn thờ gia tiên và điều kiện của từng gia đình, bộ đồ thờ bằng đồng thường được chia làm 2 quy cách chính: Bộ Tam Sự (3 món) và Bộ Ngũ Sự (5 món).",
      "### 1. Đỉnh Đồng (Lư Hương) – Trái Tim Của Bàn Thờ Gia Tiên",
      "Đỉnh đồng là pháp bảo ngự tại vị trí chính giữa bàn thờ, dùng để đốt trầm hương trong các ngày mùng Một, ngày Rằm và lễ Tết.",
      "- Ý nghĩa tâm linh: Khói trầm thơm thanh khiết tỏa ra từ miệng nghê trên nắp đỉnh có tác dụng thanh tẩy tà khí, hóa giải hung khí, kích hoạt vượng khí và kết nối lòng thành của con cháu với tổ tiên nơi cõi thiêng.",
      "- Nắp đỉnh: Đúc nổi hình tượng Con Nghê vờn cầu – linh vật thuần Việt có linh lực trấn trạch, xua đuổi tà ma và bảo hộ gia trạch bình an.",
      "- Thân đỉnh: Bầu tròn hoặc vuông quả bóng, chạm khắc nổi bộ chữ Hán - Nôm mạ vàng 'Phúc - Lộc - Thọ - Khang - Ninh' kết hợp họa tiết Song Long Chầu Nguyệt tinh xảo.",
      "- Tai mây (Quai đỉnh): Đúc liền khối với thân đỉnh, uốn lượn hình mây cách điệu vững chãi.",
      "- Chân đỉnh: 3 chân đúc liền thân theo thế 'kiềng ba chân', chạm khắc đầu hổ phù uy nghiêm chống đỡ bầu đỉnh.",
      "- Đế đỉnh: Dáng tròn hoặc bát giác, vừa khít với 3 chân đỉnh, mặt trên chạm hoa văn rồng cuộn hoặc hoa sen thanh tịnh.",
      "### 2. Đôi Hạc Đồng Cưỡi Kim Quy – Biểu Tượng Trường Thọ & Tương Trợ Âm Dương",
      "Đặt đối xứng hai bên đỉnh đồng là đôi hạc đứng trên lưng rùa, đầu ngẩng cao, miệng ngậm cành hoa sen.",
      "- Hạc: Loài chim tiên cao quý, đại diện cho phẩm hạnh thanh cao, sự thuần khiết và khí tiết của người quân tử.",
      "- Rùa (Kim Quy): Loài bò sát trường thọ, đại diện cho đất mẹ vững chãi và sự bền bỉ chở che.",
      "- Triết lý nhân sinh: Hạc đứng trên lưng rùa tượng trưng cho tình nghĩa tương trợ keo sơn giữa trời và đất, âm và dương, nhắc nhở con cháu luôn sống hòa thuận, hiếu thảo và kiên định trước sóng gió cuộc đời.",
      "### 3. Đôi Chân Nến (Đèn Thờ) – Ánh Sáng Trí Tuệ & Nhật Nguyệt Giao Hòa",
      "Được đặt ở phía ngoài cùng hai bên bàn thờ, phía trước hoặc ngang hàng với đôi hạc:",
      "- Chân nến bên trái tượng trưng cho Mặt Trời (Dương khí).",
      "- Chân nến bên phải tượng trưng cho Mặt Trăng (Âm khí).",
      "- Sự hiện diện của đôi chân nến mang ý nghĩa nhật nguyệt giao hòa, sinh sôi nảy nở, soi đường chỉ lối cho con cháu hướng về đạo đức, công danh và sự nghiệp hanh thông.",
      "## PHẦN 2: KHOA HỌC LUYỆN KIM – CÁCH PHÂN BIỆT 4 CHẤT LIỆU ĐỒNG PHỔ BIẾN TRÊN THỊ TRƯỜNG",
      "Chất liệu đúc quyết định tới 80% giá trị và tuổi thọ của một bộ đồ thờ. Dưới đây là đặc tính 4 dòng đồng đang có trên thị trường hiện nay:",
      "### 1. Đồng Vàng Thau (Đồng Thau)",
      "- Thành phần: Đồng thanh khiết 65% - 70% kết hợp hợp kim kẽm để tăng độ chảy lỏng.",
      "- Màu sắc: Màu vàng sáng bóng tự nhiên hoặc hun rêu cổ trang nghiêm.",
      "- Trọng lượng: Bộ 60cm nặng khoảng 22kg - 25kg.",
      "- Độ bền: 20 - 30 năm, thích hợp cho phân khúc gia đình cần sự trang trọng với chi phí hợp lý.",
      "### 2. Đồng Đỏ Nguyên Chất (Đồng Mắt Cua)",
      "- Thành phần: Đồng đỏ thanh khiết 90% - 95% (sử dụng dây cáp điện đỏ tuyển chọn loại 1).",
      "- Màu sắc: Màu đỏ mắt cua trầm ấm, bóng mịn, càng dùng theo năm tháng càng lên nước cổ kính.",
      "- Trọng lượng: Bộ 60cm nặng từ 28kg - 32kg, cầm rất đầm tay và chắc chắn.",
      "- Độ bền: Trường tồn trên 70 năm, không lo nứt vỡ hay bay màu.",
      "### 3. Đồng Cát-Tút (Vỏ Đạn Pháo Quân Sự)",
      "- Thành phần: Đúc từ vỏ đạn pháo quân sự nguyên chất, tính dẻo và độ đanh cơ học cực cao.",
      "- Màu sắc: Ánh vàng xanh quân sự đặc trưng, âm thanh gõ vang ngân như tiếng chuông khánh.",
      "- Độ bền: Vĩnh cửu trên 80 năm, thuộc phân khúc thượng lưu.",
      "### 4. Đồng Khảm Tam Khí / Ngũ Sắc & Mạ Vàng 24K",
      "- Cốt đồng đỏ thanh khiết chạm khắc âm bản, sau đó nghệ nhân dùng búa gõ nạm từng lá Bạc 9999 và Vàng 24k nguyên chất vào từng đường hoa văn.",
      "- Đỉnh cao mỹ nghệ truyền thống, độ tinh xảo bậc nhất, giá trị truyền đời hàng trăm năm cho con cháu.",
      "> Lời khuyên của nghệ nhân Lộc Nam: Đối với bàn thờ gia tiên lâu dài, gia chủ nên ưu tiên lựa chọn chất liệu từ Đồng Đỏ nguyên khối hoặc Đồng Cát-Tút trở lên. Đồng đỏ có tính hàn, trầm mặc, rất hợp với chốn thờ tự linh thiêng.",
      "## PHẦN 3: BẢNG TRA KÍCH THƯỚC BỘ ĐỒ THỜ THEO THƯỚC LỖ BAN CHUẨN KÍCH THƯỚC BÀN THỜ",
      "Một sai lầm rất phổ biến là gia chủ chọn bộ đỉnh quá to khiến bàn thờ chật chội, hoặc chọn bộ đỉnh quá nhỏ khiến không gian thờ bị lọt thỏm. Dưới đây là bảng quy chuẩn vàng từ xưởng Lộc Nam:",
      "- Bàn thờ dài 1m27 đến 1m55 (Sâu 61cm - 69cm): Phù hợp với bộ đỉnh đồng cao 45cm (Cung Tiến Bảo, Thêm Đinh). Khuyên dùng bộ Tam sự 45cm.",
      "- Bàn thờ dài 1m75 đến 1m97 (Sâu 81cm - 97cm): Phù hợp với bộ đỉnh đồng cao 50cm hoặc 60cm (Cung Đăng Khoa, Tài Lộc). Đây là kích thước chuẩn mực phổ biến nhất cho gia đình Việt.",
      "- Bàn thờ dài 1m97 đến 2m17 (Sâu 97cm - 107cm): Phù hợp với bộ đỉnh đồng cao 65cm hoặc 70cm (Cung Đại Cát, Quý Tử).",
      "- Bàn thờ Tổ, Từ đường, Nhà thờ họ (Dài trên 2m17): Phù hợp với bộ đỉnh đồng cao 70cm trở lên kết hợp đôi hạc đứng sàn 1m60 hoặc 1m80 uy nghi.",
      "## PHẦN 4: HƯỚNG DẪN BÀY TRÍ BÀN THỜ GIA TIÊN ĐÚNG NGUYÊN TẮC 'ĐÔNG BÌNH TÂY QUẢ'",
      "Việc sắp đặt bộ đồ thờ đúng phương vị phong thủy giúp tụ khí sinh tài, con cháu trong nhà thuận hòa, học hành đỗ đạt:",
      "- 1. Đỉnh đồng: Đặt ở vị trí chính giữa bàn thờ, lùi về phía sau cùng (sát vách tường hoặc khám thờ). Nắp nghê quay mặt nhìn thẳng ra phía trước cửa phòng thờ.",
      "- 2. Đôi Hạc: Đặt chầu hai bên đỉnh đồng, mỏ hạc hướng vào thân đỉnh. Khoảng cách từ thân đỉnh tới chân hạc từ 5cm - 10cm.",
      "- 3. Đôi Chân nến: Đặt đối xứng hai bên ngoài đôi hạc, hơi chếch về phía trước của bàn thờ để thuận tiện thắp nến ngày rằm và tạo ánh sáng ấm áp.",
      "- 4. Bát hương: Ngự tại chính diện phía trước Đỉnh đồng. Nếu gia đình thờ 3 bát hương (Thần linh ở giữa, Gia tiên bên phải, Bà cô Tổ bên trái), bát hương Thần linh phải to và kê cao hơn hai bát hương còn lại.",
      "- 5. Mâm bồng & Ngai chén: Mâm ngũ quả đặt phía trước bát hương. Ngai 3 chén hoặc 5 chén nước đặt ở mép ngoài cùng bàn thờ.",
      "## PHẦN 5: QUY TRÌNH 7 BƯỚC ĐÚC ĐỒNG THỦ CÔNG MỸ NGHỆ TẠI XƯỞNG LỘC NAM",
      "- Bước 1: Tạo mẫu đất sét định hình tỷ lệ cân đối giữa bầu đỉnh, nắp nghê và chân lân.",
      "- Bước 2: Dùng đất phù sa sông Đáy trộn trấu và giấy dó làm khuôn đúc âm dương bản, sau đó sấy nung khuôn ở 700°C liên tục 3 ngày đêm.",
      "- Bước 3: Nấu đồng đỏ nguyên chất cùng kim khí quý trong lò nung đạt nhiệt độ trên 1.200°C.",
      "- Bước 4: Rót đồng sôi đỏ rực vào khuôn đều tay, đảm bảo dòng đồng chảy liền mạch không bị rỗ bọt khí.",
      "- Bước 5: Dỡ khuôn đất sau khi đồng nguội hoàn toàn, tiến hành làm sạch cốt đồng thô nguyên khối.",
      "- Bước 6: Nghệ nhân dùng đục thép chạm khắc tay từng đường vảy rồng, chữ Hán mạ vàng, tỉa tót đuôi hạc sắc sảo từng milimet.",
      "- Bước 7: Làm màu mắt cua, hun rêu giả cổ hoặc mạ vàng 24K, cuối cùng phủ lớp sơn bóng nano 2K bảo vệ chống oxy hóa tuyệt đối.",
      "## PHẦN 6: BẢNG BÁO GIÁ BỘ ĐỒ THỜ BẰNG ĐỒNG LỘC NAM MỚI NHẤT 2026 (GIÁ GỐC TẬN XƯỞNG)",
      "- Bộ Ngũ Sự Đồng Vàng Thau 50cm - 60cm: Từ 8.500.000đ – 12.500.000đ (Bảo hành 10 năm).",
      "- Bộ Ngũ Sự Đồng Vàng Hun Rêu Cổ 60cm: Từ 11.000.000đ – 14.500.000đ (Bảo hành 15 năm).",
      "- Bộ Ngũ Sự Đồng Đỏ Nguyên Khối 60cm (nặng ~30kg): Từ 18.500.000đ – 24.000.000đ (Bảo hành 20 năm).",
      "- Bộ Ngũ Sự Đồng Cát-Tút Vỏ Đạn 60cm - 65cm: Từ 26.000.000đ – 35.000.000đ (Bảo hành trọn đời).",
      "- Bộ Ngũ Sự Khảm Tam Khí Bạc 9999 Cao Cấp: Từ 28.000.000đ – 38.000.000đ (Bảo hành trọn đời).",
      "- Bộ Ngũ Sự Mạ Vàng Ròng 24K / Dát Vàng 9999: Từ 45.000.000đ – 75.000.000đ (Bảo hành trọn đời có chứng thư giám định vàng).",
      "> Lưu ý: Giá trên đã bao gồm chi phí đóng kiện gỗ và cước vận chuyển tận nhà trên toàn quốc. Khách hàng kiểm tra đúng mẫu mã, cân nặng mới thanh toán.",
      "## PHẦN 7: CÂU HỎI THƯỜNG GẶP KHI MUA ĐỒ THỜ BẰNG ĐỒNG (FAQ)",
      "### Đồ thờ bằng đồng của Lộc Nam có bị xỉn đen hay hoen gỉ không?",
      "Sản phẩm của Đồ Đồng Lộc Nam sau khi hoàn thiện đều được xử lý bề mặt kỹ lưỡng và phủ lớp bóng 2K nano chuyên dụng ngăn chặn hoàn toàn không khí tiếp xúc với bề mặt kim loại. Sản phẩm giữ độ sáng bóng từ 15 đến trên 30 năm, chỉ cần lau bằng khăn khô mềm định kỳ.",
      "### Khách hàng ở xa (Hà Nội, Đà Nẵng, TP.HCM) đặt mua thì nhận hàng thế nào?",
      "Xưởng Lộc Nam có mạng lưới giao hàng chuyên nghiệp bằng xe tải hoặc bưu điện hỏa tốc tận nhà. Mọi đơn hàng đều được bọc xốp bóng khí và đóng thùng gỗ kín. Khi hàng tới nơi, quý khách được quyền mở kiện hàng kiểm tra kỹ lưỡng hoa văn, cân nặng trước khi thanh toán tiền.",
      "### Xưởng có nhận đúc đồ thờ, tượng đồng theo yêu cầu riêng không?",
      "Có. Chúng tôi chuyên nhận đúc đỉnh đồng cỡ đại cho nhà thờ họ, đúc tượng chân dung truyền thần cụ ông/cụ bà giống ảnh 99%, đúc chuông đồng đại hồng chung và dát vàng 9999 theo yêu cầu riêng.",
      "## PHẦN 8: LIÊN HỆ ĐẶT HÀNG TẬN XƯỞNG ĐÚC ĐỒNG LỘC NAM",
      "- Trụ sở xưởng đúc chính: Cụm Làng Nghề Đúc Đồng Truyền Thống, Huyện Ý Yên, Tỉnh Nam Định.",
      "- Website chính thức: https://www.quatanglocnam.com",
      "- Hotline / Zalo tư vấn nghệ nhân 24/7: 0846 699 997 – 0836 122 222",
      "- Email tiếp nhận bản vẽ: dodonglocnam1102@gmail.com",
      "- Thời gian mở cửa đón tiếp khách: 07:30 – 21:30 tất cả các ngày trong tuần."
    ]
  },
  {
    slug: "bi-quyet-chon-do-tho-cung-bang-dong-nam-dinh",
    title: "Bí Quyết Chọn Đồ Thờ Cúng Bằng Đồng Nam Định Chuẩn Phong Thủy Gia Tiên",
    summary: "Hướng dẫn chi tiết từ nghệ nhân Đồ Đồng Lộc Nam về cách chọn bộ đỉnh đồng, lư hương, hạc thờ theo thước Lỗ Ban và tuổi mệnh gia chủ.",
    category: "BẠN CÓ BIẾT",
    date: "27/08/2026",
    author: "Nghệ nhân Đồ Đồng Lộc Nam",
    image: "/images/do-tho-cung.jpg",
    readTime: "5 phút đọc",
    keywords: ["đồ đồng nam định", "đồ đồng đẹp", "đồ thờ cúng bằng đồng", "đồ đồng lộc nam", "đỉnh đồng ý yên"],
    content: [
      "Trong văn hóa tâm linh người Việt, không gian thờ cúng gia tiên luôn là nơi linh thiêng, tôn nghiêm nhất của ngôi nhà. Việc lựa chọn đồ thờ cúng bằng đồng chuẩn xuất xứ từ làng nghề đúc đồng truyền thống Ý Yên, Nam Định không chỉ mang lại vẻ đẹp uy nghiêm mà còn tích tụ vượng khí, tài lộc cho gia đạo.",
      "### 1. Tại sao nên chọn đồ đồng Nam Định?",
      "Làng nghề đúc đồng Ý Yên – Nam Định với lịch sử hơn 900 năm được mệnh danh là cái nôi của nghệ thuật đúc đồng Việt Nam. Đồ Đồng Lộc Nam tại Nam Định sử dụng 100% phôi đồng đỏ, đồng catut thanh khiết, được nung chảy ở nhiệt độ trên 1200 độ C và đúc thủ công nguyên khối.",
      "Ưu điểm nổi bật của đồ đồng Nam Định:",
      "- Độ bền vĩnh cửu: Đồng thanh khiết không bị giòn, nứt hay bong tróc theo thời gian.",
      "- Hoa văn chạm khắc tinh xảo: Từng họa tiết Rồng chầu mặt nguyệt, Hoa sòi, Nghê vờn cầu được nghệ nhân chạm khắc tay sắc nét.",
      "- Màu sắc cổ kính, sang trọng: Được hun màu giả cổ hoặc mạ vàng 24k, dát vàng 9999 cao cấp.",
      "### 2. Chọn kích thước bộ đồ thờ theo thước Lỗ Ban",
      "Kích thước bộ đỉnh đồng (bộ tam sự, ngũ sự) cần tương xứng với kích thước bàn thờ gia tiên:",
      "- Bàn thờ dài 1m27 – 1m55: Phù hợp với bộ đỉnh đồng cao 45cm – 50cm.",
      "- Bàn thờ dài 1m75 – 1m97: Phù hợp với bộ ngũ sự cao 60cm – 65cm.",
      "- Bàn thờ dài trên 2m17 (từ đường, nhà thờ họ): Phù hợp với bộ ngũ sự cao 70cm trở lên.",
      "### 3. Địa chỉ mua đồ đồng đẹp uy tín",
      "Xưởng đúc Đồ Đồng Lộc Nam tự hào là đơn vị trực tiếp sản xuất và phân phối các mẫu đồ đồng đẹp, đồ thờ cúng cao cấp không qua trung gian. Quý khách hàng được kiểm tra hàng trước khi thanh toán và nhận phiếu bảo hành trọn đời chất lượng đồng."
    ]
  },
  {
    slug: "quy-trinh-duc-tuong-dong-chan-dung-truyen-than",
    title: "Quy Trình Đúc Đồng Chân Dung Truyền Thần Giống Thật 100% Của Xưởng Lộc Nam",
    summary: "Khám phá kỹ thuật đúc tượng chân dung ông bà, cha mẹ, danh nhân bằng đồng đỏ nguyên khối đạt độ giống và thần thái tới 99.9%.",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "26/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/4.jpg",
    readTime: "7 phút đọc",
    keywords: ["đúc đồng chân dung", "đúc tượng chân dung", "đồ đồng lộc nam", "tượng đồng nam định", "đúc tượng truyền thần"],
    content: [
      "Dịch vụ đúc đồng chân dung truyền thần để báo hiếu cha mẹ, tưởng nhớ tổ tiên hoặc tôn vinh các bậc tiền nhân, danh nhân lịch sử đang là xu hướng được nhiều gia đình và tổ chức lựa chọn.",
      "Tuy nhiên, đúc tượng chân dung là phân khúc khó nhất trong nghệ thuật đúc đồng vì đòi hỏi không chỉ tay nghề kỹ thuật mà còn phải truyền tải được cái thần, nét mặt và thần thái sống động của nhân vật.",
      "### Quy trình 5 bước đúc tượng chân dung tại Đồ Đồng Lộc Nam:",
      "1. Tạo mẫu đất sét (Khâu quan trọng nhất): Dựa trên hình ảnh chụp đa góc độ của nhân vật, điêu khắc gia đắp mẫu đất sét tỷ lệ 1:1. Khách hàng sẽ được xem trực tiếp hoặc duyệt qua video/ảnh để chỉnh sửa từng đường nét mắt, mũi, nụ cười đến khi ưng ý 100%.",
      "2. Làm khuôn thạch cao & khuôn composite: Chuyển mẫu đất sang khuôn âm bản chịu nhiệt đặc biệt để giữ nguyên từng chi tiết vi mô.",
      "3. Luyện đồng & Nấu đồng đỏ: Sử dụng đồng đỏ thanh khiết (đồng dây điện loại 1), pha tỷ lệ thiếc và kẽm chuẩn xác để dòng chảy đồng mịn và đều.",
      "4. Rót đồng vào khuôn: Nghệ nhân canh nhiệt độ rót đều tay, hạn chế tối đa bọt khí.",
      "5. Làm nguội, chạm tỉa & mạ dát vàng: Dũa gọt, chạm trổ từng sợi tóc, nếp nhăn và hoàn thiện bề mặt (phủ bóng nano, mạ vàng 24k hoặc dát vàng 9999).",
      "### Cam kết chất lượng từ Đồ Đồng Lộc Nam:",
      "Tất cả các sản phẩm đúc đồng chân dung tại xưởng Lộc Nam đều được bảo đảm độ giống thực tế, đúc liền khối vững chắc trường tồn cùng thời gian."
    ]
  },
  {
    slug: "top-mau-do-dong-dep-tinh-xao-nhat-nam-nay",
    title: "Top Các Mẫu Đồ Đồng Đẹp, Tinh Xảo Được Ưa Chuộng Nhất Năm Nay",
    summary: "Tổng hợp các kiệt tác đồ đồng mỹ nghệ: tượng Bác Hồ, tượng Trần Hưng Đạo, đỉnh đồng khảm ngũ sắc thất lân và tranh đồng mạ vàng.",
    category: "BẠN CÓ BIẾT",
    date: "25/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/bo-do-tho-ma-vang.jpg",
    readTime: "4 phút đọc",
    keywords: ["đồ đồng đẹp", "đồ đồng nam định", "đồ đồng lộc nam", "tượng đồng phong thủy", "bộ ngũ sự khảm ngũ sắc"],
    content: [
      "Thị trường mỹ nghệ ngày càng phát triển với nhiều sản phẩm đồng đúc cao cấp. Dưới đây là danh sách những mẫu đồ đồng đẹp được các gia chủ, doanh nhân và nhà sưu tầm săn đón nhiều nhất hiện nay:",
      "### 1. Bộ Ngũ Sự Khảm Ngũ Sắc Thất Lân Vờn Cầu",
      "Đỉnh đồng thất lân kết hợp đôi chân nến và đôi hạc thờ được khảm 5 kim loại quý: Vàng 9999, Bạc trắng, Đồng đỏ, Đồng xanh và Đồng đen. Từng đường khảm chìm sâu vào phôi đồng tạo nên hoa văn sống động và uy nghiêm trên ban thờ.",
      "### 2. Tượng Trần Quốc Tuấn Đồng Catut Cao Cấp",
      "Bức tượng Quốc Công Tiết Chế Hưng Đạo Đại Vương cầm hịch tướng sĩ đúc từ vỏ đạn quân sự (đồng catut) màu vàng ánh kim rực rỡ, mang năng lượng trấn trạch, trừ tà và đem lại uy quyền cho gia chủ.",
      "### 3. Tượng Bác Hồ Ngồi Ghế Mây Mạ Vàng 24K",
      "Tác phẩm tượng đồng chân dung Bác Hồ với thần thái ung dung, hiền từ là quà tặng ngoại giao và vật phẩm trang trọng hàng đầu tại các cơ quan, hội trường và phòng lưu niệm.",
      "### 4. Tranh Đồng Vinh Hoa Phú Quý 2m3 Mạ Vàng Dát Bạc",
      "Bức tranh phong cảnh cây tùng, chim hạc, hoa cúc, cuốn thư mang ý nghĩa cầu chúc tài lộc, gia đình sung túc, con cháu vinh hiển."
    ]
  },
  {
    slug: "y-nghia-phong-thuy-trong-dong-dong-son",
    title: "Ý Nghĩa Phong Thủy Trống Đồng Đông Sơn Trong Phòng Khách & Cơ Quan",
    summary: "Tại sao các doanh nhân thành đạt và cơ quan nhà nước luôn đặt trống đồng Đông Sơn tại vị trí trang trọng nhất?",
    category: "KIẾN THỨC ĐỒ ĐỒNG",
    date: "24/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/locnam_real/locnam_trong_dong.jpg",
    readTime: "6 phút đọc",
    keywords: ["trống đồng đông sơn", "đồ đồng đẹp", "đồ đồng nam định", "quà tặng trống đồng", "đồ đồng lộc nam"],
    content: [
      "Trống đồng Đông Sơn không chỉ là bảo vật biểu tượng cho nền văn minh sông Hồng mà còn là vật phẩm phong thủy mang quyền năng trấn trạch và thu hút linh khí cực mạnh.",
      "### 1. Ý nghĩa biểu tượng của mặt trống đồng",
      "- Tâm trống (Mặt trời): Đại diện cho nguồn sống vô tận, ánh sáng xua tan tà khí và bóng tối, soi đường chỉ lối cho gia chủ hanh thông trong sự nghiệp.",
      "- Hình tượng chim Lạc bay ngược chiều kim đồng hồ: Tượng trưng cho dòng chảy thời gian và cội nguồn bất diệt của dân tộc Việt.",
      "- Cảnh sinh hoạt giã gạo, múa hát, chèo thuyền: Thể hiện sự ấm no, đoàn kết và sinh sôi nảy nở của tài lộc.",
      "### 2. Vị trí đặt trống đồng hợp phong thủy",
      "- Phòng khách: Đặt trên đôn gỗ cao 60cm – 80cm tại hướng Tây Bắc hoặc chính Bắc để kích hoạt tài vận.",
      "- Phòng làm việc / Phòng giám đốc: Đặt sau lưng bàn làm việc hoặc trên kệ tủ tài liệu tạo điểm tựa vững chắc, nâng cao uy quyền.",
      "- Phòng họp & Hội trường: Đặt mô hình trống đồng lớn ở trung tâm mang lại sự trang nghiêm và thịnh vượng bền lâu."
    ]
  },
  {
    slug: "cach-phan-biet-do-dong-that-va-dong-pha-tap-chat",
    title: "5 Cách Phân Biệt Đồ Đồng Thật và Đồng Pha Tạp Chất Đơn Giản Nhất",
    summary: "Cẩm nang bỏ túi giúp người mua không bị mắc bẫy đồng Đài Loan mạ màu hoặc đồng pha chì kém chất lượng.",
    category: "BẠN CÓ BIẾT",
    date: "23/08/2026",
    author: "Đồ Đồng Lộc Nam",
    image: "/images/artisan-foundry.jpg",
    readTime: "5 phút đọc",
    keywords: ["phân biệt đồ đồng", "đồ đồng nam định", "đồ đồng đẹp", "đồ đồng lộc nam", "mua đồ đồng uy tín"],
    content: [
      "Hiện nay trên thị trường có nhiều loại đồ đồng công nghiệp mạ xi mỏng hoặc đồng pha nhiều chì, kẽm chỉ sau 6 tháng đến 1 năm là bị bong tróc, xỉn đen không thể phục hồi.",
      "Dưới đây là 5 mẹo từ nghệ nhân xưởng Đồ Đồng Lộc Nam giúp bạn nhận biết ngay đồng thật chuẩn chất lượng:",
      "### 1. Kiểm tra bằng trọng lượng",
      "Đồ đồng thủ công Nam Định đúc bằng đồng thanh khiết thành dày bản nên cầm rất đầm tay, nặng hơn đáng kể so với đồ đồng dập máy công nghiệp mỏng rỗng ruột.",
      "### 2. Kiểm tra bằng âm thanh (tiếng chuông)",
      "Khi dùng thanh kim loại gõ nhẹ vào thân đỉnh đồng hoặc tượng đồng thật, âm thanh phát ra sẽ vang trầm, ấm và ngân dài. Trong khi đó đồng pha tạp chất hoặc đồng mỏng sẽ kêu cạch cạch đanh ngắn.",
      "### 3. Kiểm tra bằng lửa",
      "Đồng thật nguyên chất có nhiệt độ nóng chảy rất cao (> 1000°C). Khi hơ ngọn lửa gas vào bề mặt, đồng xịn không hề biến đổi màu hay bong tróc, chỉ cần lau nhẹ tàn khói là sáng bóng như mới.",
      "### 4. Kiểm tra đường nét hoa văn",
      "Đồ đồng thủ công mỹ nghệ có hoa văn chạm trổ thủ công mềm mại, sắc sảo từng milimet, không có vết ráp thô kệch hay ba-via lởm chởm như hàng đúc máy giá rẻ.",
      "### 5. Chọn cơ sở có cam kết bảo hành",
      "Hãy mua tại các xưởng đúc trực tiếp có thương hiệu như Đồ Đồng Lộc Nam – có địa chỉ xưởng rõ ràng tại làng nghề đúc đồng Ý Yên Nam Định và cam kết bảo hành trọn đời bằng văn bản."
    ]
  }
];
